#!/usr/bin/env python3
"""Original bilingual lesson specifications for Chapter 04."""

from __future__ import annotations

from typing import Any


COMMON_REFS = {
    "cuda_programming": (
        "CUDA Programming Guide",
        "https://docs.nvidia.com/cuda/cuda-programming-guide/",
    ),
    "cuda_best": (
        "CUDA C++ Best Practices Guide",
        "https://docs.nvidia.com/cuda/cuda-c-best-practices-guide/",
    ),
    "torch_cuda": (
        "PyTorch CUDA semantics",
        "https://docs.pytorch.org/docs/stable/notes/cuda.html",
    ),
    "torch_sdpa": (
        "PyTorch scaled dot product attention",
        "https://docs.pytorch.org/docs/stable/generated/torch.nn.functional.scaled_dot_product_attention.html",
    ),
    "flashattention": (
        "FlashAttention: Fast and Memory-Efficient Exact Attention with IO-Awareness",
        "https://arxiv.org/abs/2205.14135",
    ),
    "a100_whitepaper": (
        "NVIDIA A100 Tensor Core GPU Architecture Whitepaper",
        "https://www.nvidia.com/content/dam/en-zz/Solutions/Data-Center/nvidia-ampere-architecture-whitepaper.pdf",
    ),
    "hbm_package": (
        "Inside Pascal: NVIDIA's Newest Computing Platform",
        "https://developer.nvidia.com/blog/inside-pascal/",
    ),
    "micron_memory": (
        "Micron Introduction to Memory",
        "https://www.micron.com/content/dam/micron/educatorhub/intro-to-memory/MicronIntroduction-to-Memory-Presentation.pdf",
    ),
    "roofline": (
        "NVIDIA Nsight Compute Roofline Analysis",
        "https://developer.nvidia.com/blog/accelerating-hpc-applications-with-nsight-compute-roofline-analysis/",
    ),
    "rtx5090": (
        "NVIDIA GeForce RTX 5090 specifications",
        "https://www.nvidia.com/en-us/geforce/graphics-cards/50-series/rtx-5090/",
    ),
}


def L(
    no: int,
    slug: str,
    title_en: str,
    title_zh: str,
    puzzle_en: str,
    puzzle_zh: str,
    hook_en: str,
    hook_zh: str,
    mechanism_en: str,
    mechanism_zh: str,
    anchors_en: list[str],
    anchors_zh: list[str],
    predictions_en: list[str],
    predictions_zh: list[str],
    experiment_en: str,
    experiment_zh: str,
    baseline_en: str,
    baseline_zh: str,
    candidate_en: str,
    candidate_zh: str,
    controlled_en: str,
    controlled_zh: str,
    metrics_en: str,
    metrics_zh: str,
    code_en: str,
    code_zh: str,
    conclusion_en: str,
    conclusion_zh: str,
    failure_en: str,
    failure_zh: str,
    extend_en: str,
    extend_zh: str,
    evidence_label: str,
    result_fields: list[tuple[str, str, str, str]],
    refs: list[str],
    visuals: list[tuple[str, str, str]],
    mermaid: str,
) -> dict[str, Any]:
    return locals()


LESSONS: list[dict[str, Any]] = [
    L(
        1,
        "cmos-switching-dynamic-power",
        "CMOS Switching, State, and Dynamic Power",
        "CMOS 开关、状态与动态功耗",
        "A transistor stores no Python value, so how can billions of switches implement state—and why does voltage dominate switching energy?",
        "晶体管并不保存 Python 变量，数十亿个开关如何组成状态？为什么电压会主导切换能耗？",
        "GPU performance begins with a physical transition. A CMOS inverter maps an input voltage to one of two stable output regions; cross-coupled inverters can then hold a bit. The useful systems connection is not transistor trivia. Every clocked transition charges or discharges capacitance, so activity, voltage, capacitance, and frequency set a first-order power envelope long before CUDA exposes a kernel.",
        "GPU 性能的起点是一次真实的电压翻转。CMOS 反相器把输入电压映射到两个稳定输出区，两个反相器交叉耦合后便能保持一位状态。这里关心的不是背电路名词，而是建立系统直觉：每次时钟切换都要给电容充放电，活动率、电压、电容和频率共同构成功耗上限。",
        "For one effective capacitance, a 0→1 transition draws roughly `C·V²` from the supply; about half is stored and the rest is dissipated, then the stored energy is dissipated on discharge. A common activity-averaged model is `P_dynamic ≈ α·C·V²·f`. It is a model, not a board-power meter: leakage, short-circuit current, clock trees, memories, regulators, and workload placement add terms. The experiment keeps the equation explicit and sweeps one variable at a time so the quadratic voltage dependence cannot be confused with a measured GPU wattage claim.",
        "单个等效电容从 0 充到 1 时，电源提供的能量量级为 `C·V²`；常见的平均动态功耗模型是 `P_dynamic ≈ α·C·V²·f`。这是解释变量关系的一阶模型，不是显卡功耗计：漏电、短路电流、时钟树、片上存储、电源转换和任务放置都会增加额外项。实验固定其他变量，分别扫描电压、频率和活动率，让平方关系直接可见。",
        [
            "Logic state is represented by voltage ranges, not by a software type.",
            "Cross-coupled feedback creates state; an isolated inverter only transforms a signal.",
            "The `V²` term makes voltage changes more consequential than equal percentage frequency changes in this model.",
        ],
        [
            "逻辑状态由电压区间表示，不由软件类型表示。",
            "交叉反馈形成可保持的状态；单个反相器只负责变换信号。",
            "模型中的 `V²` 说明：相同比例下，电压变化比频率变化更敏感。",
        ],
        [
            "Predict the inverter output for low and high inputs.",
            "Predict the energy ratio between 1.0 V and 0.8 V at fixed capacitance.",
            "Name two power terms that the dynamic model omits.",
        ],
        [
            "先判断输入为低、高电平时反相器的输出。",
            "在电容不变时，预测 1.0 V 与 0.8 V 的切换能量比。",
            "写出动态功耗模型没有覆盖的两个功耗来源。",
        ],
        "Evaluate the inverter truth table and sweep the transparent `αCV²f` model.",
        "验证反相器真值表，并扫描透明的 `αCV²f` 模型。",
        "1.0 V, 1 GHz, fixed effective capacitance and activity",
        "1.0 V、1 GHz，固定等效电容与活动率",
        "0.8 V and changed activity/frequency scenarios",
        "0.8 V，以及改变活动率或频率的场景",
        "capacitance, activity, and the selected sweep variable",
        "电容、活动率及当前扫描之外的变量",
        "energy per transition, dynamic power, and voltage energy ratio",
        "单次切换能量、动态功耗和电压能量比",
        "The code expresses the equations directly in SI units, then reports femtojoules and milliwatts for readable scales. It does not query board power or infer a voltage-frequency curve from the GPU.",
        "代码直接用 SI 单位计算，再把结果转换为飞焦耳和毫瓦。它不会读取显卡板级功耗，也不会用这个公式反推 GPU 的电压—频率曲线。",
        "Use `αCV²f` to reason about direction and sensitivity; use hardware telemetry and controlled workloads to measure an actual GPU.",
        "用 `αCV²f` 判断方向和敏感度；判断真实 GPU 功耗时，必须回到硬件遥测与受控工作负载。",
        "The effective capacitance and voltage are illustrative. Real dynamic voltage/frequency scaling changes several variables together, and leakage can become important at different process and temperature points.",
        "等效电容和电压只是教学参数。真实 DVFS 会同时改变多个变量，不同工艺与温度下漏电占比也会变化。",
        "Collect board-power samples for a fixed CUDA workload at several locked clocks, then compare measured deltas with the model's direction rather than forcing an exact fit.",
        "对固定 CUDA 工作负载锁定多个频点采集板级功耗，只比较实测变化方向，不强求与一阶模型精确拟合。",
        "numerical-model",
        [("Energy at 1.0 V", "1.0 V 切换能量", "energy_1v_fj", "float"), ("Energy at 0.8 V", "0.8 V 切换能量", "energy_08v_fj", "float"), ("Energy ratio", "能量比", "voltage_energy_ratio", "ratio"), ("Baseline dynamic power", "基线动态功耗", "power_1v_mw", "float")],
        ["cuda_programming", "a100_whitepaper"],
        [("assets/visualizations/cmos-inverter.png", "CMOS inverter states", "CMOS 反相器状态图"), ("assets/visualizations/cmos-inverter.html", "Interactive inverter visualization", "交互式反相器图")],
        'flowchart LR\n  A["input voltage"] --> B["PMOS/NMOS conduction"]\n  B --> C["output capacitance charges or discharges"]\n  C --> D["logic state"]\n  C --> E["dynamic energy ≈ C·V²"]',
    ),
    L(
        2,
        "dram-1t1c-charge-sharing",
        "1T1C DRAM: Charge Sharing, Sensing, and Restore",
        "1T1C DRAM：电荷共享、感放与恢复",
        "If a DRAM cell is only one transistor and one tiny capacitor, how can a read recover a reliable bit without preserving the original charge?",
        "DRAM 单元只有一个晶体管和一个微小电容，读取时电荷还会被扰动，它如何可靠恢复一位数据？",
        "A 1T1C cell trades circuit area for a demanding read protocol. The wordline turns on an access transistor, the cell capacitor shares charge with a much larger bitline precharged near `VDD/2`, and a sense amplifier turns the small deviation into a full logic level. Because the access changes the cell charge, sensing is followed by restore; leakage later requires refresh.",
        "1T1C 单元用更少的面积换来更复杂的读取流程。字线打开访问晶体管，单元电容与预充到 `VDD/2` 附近的位线发生电荷共享，感应放大器再把微小偏差放大成完整逻辑电平。读取改变了原有电荷，因此感放之后还必须恢复；电容漏电则要求周期性刷新。",
        "Ignoring parasitics, shared voltage is `(Ccell·Vcell + Cbit·Vpre)/(Ccell + Cbit)`. The signal margin is the absolute deviation from precharge. Increasing bitline capacitance reduces that margin; lowering retained cell voltage does the same. The notebook sweeps both effects and records the restore target. This numerical result explains the mechanism, but it does not identify a proprietary DRAM timing or analog sense-amplifier design.",
        "忽略寄生项时，共享后的电压为 `(Ccell·Vcell + Cbit·Vpre)/(Ccell + Cbit)`，感放看到的信号就是它相对预充电压的偏移。位线电容越大，偏移越小；单元电压因漏电降低时，偏移也会减小。Notebook 同时扫描这两个因素，并记录恢复目标。它解释的是机制，不会声称还原某个商业 DRAM 的模拟电路参数。",
        ["Precharge creates a neutral reference near `VDD/2`.", "Charge sharing produces a small analog deviation before a digital bit exists.", "Read, sense, and restore are one protocol; omitting restore loses the state."],
        ["预充电在 `VDD/2` 附近建立中性参考。", "电荷共享先产生微小模拟偏移，之后才得到数字位。", "读取、感放和恢复是同一流程，缺少恢复就会丢失状态。"],
        ["Predict whether a stored 1 moves the bitline above or below precharge.", "Predict how a 10× larger bitline capacitance changes the sensing margin.", "Explain why the read is called destructive."],
        ["判断存储 1 会让位线高于还是低于预充电压。", "预测位线电容增大 10 倍时感放裕量如何变化。", "解释为什么 DRAM 读取被称为破坏性读取。"],
        "Compute charge-sharing voltage and sensing margin over capacitance and retention sweeps.",
        "计算不同电容比与保持电压下的共享电压和感放裕量。",
        "fresh cell at 1.0 V with a 10× bitline-to-cell capacitance ratio",
        "新鲜的 1.0 V 单元，位线电容为单元电容的 10 倍",
        "larger bitlines and leaked cell voltage",
        "更大的位线电容与发生漏电后的单元电压",
        "VDD, precharge voltage, and ideal charge conservation",
        "VDD、预充电压及理想电荷守恒假设",
        "shared voltage, sensing margin, and margin loss",
        "共享电压、感放裕量和裕量损失",
        "The experiment uses a small pure-Python function for the conservation equation, sweeps explicit values, and checks that a restored 1 returns to VDD. No latency number is manufactured from the model.",
        "实验用一个纯 Python 函数实现电荷守恒方程，显式扫描参数，并检查逻辑 1 在恢复后回到 VDD。模型不会凭空生成 DRAM 延迟。",
        "Treat sensing margin as the bridge between capacitor physics and a reliable digital bit; restore and refresh are required parts of the storage contract.",
        "把感放裕量看作电容物理与可靠数字位之间的桥梁；恢复与刷新都是存储协议的一部分。",
        "Parasitic capacitance, noise, temperature, variation, equalization, and sense-amplifier offset are omitted. The model is useful for direction, not for sign-off.",
        "模型省略了寄生电容、噪声、温度、工艺偏差、均衡电路和感放失调，只适合判断方向，不能用于芯片签核。",
        "Add a noise and offset distribution, then estimate a margin-failure probability rather than reporting only the nominal voltage.",
        "加入噪声与失调分布，把名义电压扩展为感放裕量失效概率。",
        "numerical-model",
        [("Fresh-cell margin", "新鲜单元裕量", "fresh_margin_mv", "float"), ("Leaked-cell margin", "漏电后裕量", "leaked_margin_mv", "float"), ("Margin retained", "保留的裕量", "margin_retained", "percent"), ("Restore target", "恢复目标", "restore_target_v", "float")],
        ["micron_memory", "cuda_programming"],
        [("assets/1T1C_DRAM_Cell.png", "1T1C DRAM cell", "1T1C DRAM 单元"), ("assets/visualizations/dram-1t1c-read-mechanism.png", "DRAM read mechanism", "DRAM 读取机制"), ("assets/visualizations/dram-1t1c-read-mechanism.html", "Interactive DRAM read visualization", "交互式 DRAM 读取图")],
        'flowchart LR\n  A["bitline precharge"] --> B["wordline opens access transistor"]\n  B --> C["cell and bitline share charge"]\n  C --> D["sense amplifier resolves deviation"]\n  D --> E["cell is restored"]',
    ),
    L(
        3,
        "gpu-memory-spatial-hierarchy",
        "GPU Memory as a Spatial Hierarchy",
        "GPU 存储器的空间层级",
        "Why can the same byte be cheap in a register and expensive in external memory even when its numerical value never changes?",
        "同一个字节的数值没有变化，为什么放在寄存器里很便宜，放在外部显存里却很贵？",
        "GPU memory names also describe physical placement and sharing scope. Registers and shared memory sit inside an SM; L2 is shared across SMs on the GPU die; HBM or GDDR is outside the die and reached through controllers and physical links. Capacity tends to increase outward while latency, energy, and sharing distance also increase. CUDA's address spaces are a programming interface over this physical hierarchy, not a one-to-one schematic.",
        "GPU 的存储器名称同时说明物理位置和共享范围。寄存器与 shared memory 位于 SM 内部，L2 位于 GPU die 上并由多个 SM 共享，HBM 或 GDDR 位于 die 外，需要经过内存控制器和物理链路。越向外容量通常越大，但访问延迟、能耗和共享距离也会上升。CUDA 地址空间是这套物理层级之上的编程接口，并不等于逐电路映射。",
        "The lesson builds an explicit hierarchy record with capacity, modeled latency, scope, and technology, then evaluates the same working set under different reuse assumptions. A byte fetched once from external memory and reused many times on chip amortizes the outer transfer. A byte streamed once does not. The model therefore records both distance and reuse instead of ranking memories by a single latency number.",
        "实验建立一个包含容量、示意延迟、共享范围和存储技术的层级表，再比较同一工作集在不同复用次数下的搬运成本。从外部显存取入一次、在片上重复使用多次，可以摊薄外层传输；只读一次的流式数据则不能。因此需要同时观察访问距离和复用次数，而不是只背一张延迟表。",
        ["Registers/shared memory, L2, and external memory occupy different physical regions.", "Capacity, scope, latency, and bandwidth are separate axes.", "Reuse changes how often the expensive outer path is paid."],
        ["寄存器/shared memory、L2 与外部显存位于不同物理区域。", "容量、共享范围、延迟与带宽是四个不同维度。", "复用决定昂贵的外层路径要付多少次。"],
        ["Place registers, shared memory, L2, and HBM/GDDR from nearest to farthest from an SM.", "Predict the outer-memory bytes for reuse counts 1 and 32.", "Explain why CUDA local memory is not necessarily on-chip."],
        ["按离 SM 从近到远排列寄存器、shared memory、L2 与 HBM/GDDR。", "预测复用次数为 1 和 32 时的外部显存字节数。", "解释为什么 CUDA local memory 不一定在片上。"],
        "Evaluate an explicit hierarchy and amortize external traffic over reuse.",
        "建立显式层级表，并用复用次数摊薄外部流量。",
        "one-pass streaming of a fixed working set",
        "固定工作集只流式读取一次",
        "the same working set staged once and reused on chip",
        "同一工作集只搬入一次并在片上复用",
        "working-set bytes and hierarchy assumptions",
        "工作集大小与层级假设",
        "modeled access ratio and external bytes per use",
        "示意访问比与每次使用对应的外部字节",
        "The code keeps the hierarchy as data rather than hiding it in prose. It computes bytes per logical use for several reuse counts and prints the actual CUDA device memory capacity as an environment fact.",
        "代码把层级写成可检查的数据，计算多种复用次数下每次逻辑使用对应的外部字节，并把 CUDA 设备显存容量作为真实环境事实打印出来。",
        "Optimize placement only after naming scope and reuse; 'faster memory' without a tile lifetime and sharing contract is incomplete.",
        "只有明确共享范围和复用方式后才能讨论放置；脱离 tile 生命周期与共享契约的“更快内存”并不完整。",
        "Latency values are educational ratios, not microbenchmarks. Cache replacement, compiler decisions, occupancy, and contention can change the realized path.",
        "延迟值只是教学比例，不是微基准结果。缓存替换、编译器决策、occupancy 与竞争都会改变实际路径。",
        "Use Nsight Compute counters to measure DRAM, L2, and L1/shared traffic for a tiled kernel and compare the measured reuse to the model.",
        "用 Nsight Compute 采集 tiled kernel 的 DRAM、L2 与 L1/shared 流量，把实测复用率与模型对照。",
        "capacity-model",
        [("Device memory", "设备显存", "device_memory_gib", "float"), ("Streaming bytes/use", "流式场景每次字节", "bytes_per_use_streaming", "bytes"), ("32× reuse bytes/use", "32 次复用每次字节", "bytes_per_use_reuse32", "bytes"), ("Traffic reduction", "流量降低倍数", "reuse32_reduction", "ratio")],
        ["cuda_programming", "a100_whitepaper"],
        [("assets/visualizations/gpu-memory-spatial-layout.png", "GPU memory spatial layout", "GPU 存储空间布局"), ("assets/visualizations/gpu-memory-spatial-layout.html", "Interactive memory layout", "交互式存储布局")],
        'flowchart LR\n  A["registers"] --> B["shared memory / L1"]\n  B --> C["L2 slices"]\n  C --> D["memory controllers"]\n  D --> E["HBM or GDDR"]',
    ),
    L(
        4,
        "data-movement-roofline",
        "Why Data Movement Can Cost More Than Arithmetic",
        "为什么数据搬运可能比计算更贵",
        "If a GPU can execute enormous arithmetic throughput, why can a simple elementwise operation remain slow?",
        "GPU 拥有很高的算力，为什么一个简单的逐元素操作仍可能很慢？",
        "An operation cannot use a compute unit until its operands arrive. Moving data activates wires, buffers, routing, tags, controllers, and storage arrays across distance; a multiply-add reusing values already near an execution unit may perform far more useful arithmetic per transferred byte. Arithmetic intensity—operations divided by bytes moved—connects an algorithm to this physical distinction.",
        "执行单元拿到操作数之后才能计算。数据搬运会沿途激活连线、缓冲区、路由、标签、控制器和存储阵列；而一组已经靠近执行单元的数据可以被乘加多次。算术强度，即每搬运一个字节完成多少运算，把算法结构与这种物理差异连接起来。",
        "The Roofline bound is `min(peak_compute, bandwidth × arithmetic_intensity)`. Vector addition has low intensity because it reads two arrays and writes one for one addition. A large matrix multiplication reuses each tile and can have much higher intensity. The notebook measures a vector operation and BF16 GEMM through the same CUDA-event helper, reports effective bandwidth or TFLOP/s, and keeps analytical bytes/FLOPs beside time. The two metrics are not compared as if they were interchangeable.",
        "Roofline 上限为 `min(峰值算力, 带宽 × 算术强度)`。向量加法为一次加法读取两个数组、写回一个数组，算术强度很低；大矩阵乘利用 tile 复用数据，强度可高得多。Notebook 用同一套 CUDA Event 方法分别测量向量运算和 BF16 GEMM，同时保留分析字节数、FLOP 数、有效带宽与 TFLOP/s，不把这些指标混为一个排名。",
        ["Performance needs both an operation count and a byte count.", "Low intensity puts the bandwidth roof below the compute roof.", "Tiling and fusion help when they remove or amortize traffic, not merely because they add code."],
        ["性能分析必须同时有运算量和字节量。", "算术强度低时，带宽屋顶会先于算力屋顶限制性能。", "tiling 与 fusion 的价值在于减少或摊薄流量，而不是代码更复杂。"],
        ["Predict which workload is closer to a bandwidth ceiling.", "Compute vector-add intensity assuming two reads and one write.", "Name one reason achieved values stay below either theoretical roof."],
        ["判断哪种工作负载更接近带宽上限。", "按两次读取、一次写回计算向量加法强度。", "写出实测性能低于理论屋顶的一个原因。"],
        "Measure a low-intensity vector expression and a reuse-heavy BF16 GEMM on one GPU.",
        "在同一 GPU 上测量低强度向量表达式和高复用 BF16 GEMM。",
        "elementwise `a + b` over a large tensor",
        "大张量上的逐元素 `a + b`",
        "square BF16 matrix multiplication",
        "方形 BF16 矩阵乘",
        "GPU, warm-up, repetitions, dtype, and event timing",
        "GPU、warm-up、重复次数、dtype 与 Event 计时方式",
        "arithmetic intensity, median latency, effective GB/s, and TFLOP/s",
        "算术强度、中位延迟、有效 GB/s 与 TFLOP/s",
        "The vector path counts compulsory tensor traffic; the GEMM path uses `2MNK` FLOPs and input/output bytes as an algorithmic intensity estimate. Library internals and cache traffic are left as measured follow-ups.",
        "向量路径统计必要张量流量；GEMM 以 `2MNK` 计算 FLOP，并用输入输出字节估算算法强度。库内部实现与缓存流量留给 profiler 实测。",
        "Choose the next optimization from the limiting resource: reduce traffic for a bandwidth-bound kernel and improve math utilization only when compute is the credible ceiling.",
        "先判断限制资源：带宽受限时优先减少流量，只有算力确实构成上限时才优先提高数学单元利用率。",
        "Effective bandwidth is based on requested tensor bytes, not every physical transaction. GEMM may use implementation-specific precision and kernels. Shape changes can reverse the comparison.",
        "有效带宽只按请求的张量字节计算，并不等于全部物理传输。GEMM 还会受到具体精度、kernel 与 shape 的影响。",
        "Profile both operations with hierarchical Roofline counters and add a fused elementwise candidate that eliminates one intermediate write.",
        "用分层 Roofline counter 分析两种操作，再增加一个消除中间写回的 fused elementwise candidate。",
        "pytorch-gpu",
        [("Vector median", "向量中位延迟", "vector_median_ms", "ms"), ("Vector effective bandwidth", "向量有效带宽", "vector_effective_gbps", "float"), ("GEMM median", "GEMM 中位延迟", "gemm_median_ms", "ms"), ("GEMM throughput", "GEMM 吞吐", "gemm_tflops", "float"), ("GEMM intensity", "GEMM 算术强度", "gemm_intensity_flop_byte", "float")],
        ["roofline", "cuda_best"],
        [],
        'flowchart LR\n  A["algorithm"] --> B["FLOPs"]\n  A --> C["bytes moved"]\n  B --> D["arithmetic intensity"]\n  C --> D\n  D --> E["bandwidth or compute roof"]',
    ),
    L(
        5,
        "sm-tensor-core-data-path",
        "Feeding the SM and Tensor Cores",
        "向 SM 与 Tensor Core 喂数",
        "Why can a Tensor Core capable GPU underperform when a matrix shape is only slightly awkward?",
        "GPU 明明有 Tensor Core，为什么矩阵形状稍微别扭就可能发挥不好？",
        "Tensor Cores are execution units inside an SM, not autonomous matrix servers. Instructions must be scheduled, operands must be fetched from register banks and collectors, and tiles must match a supported dtype and layout. Memory, instruction issue, dependency tracking, register pressure, and tile geometry can all prevent the arithmetic pipeline from staying full.",
        "Tensor Core 是 SM 内部的执行单元，不是一台自动接单的矩阵服务器。指令需要被调度，操作数要从寄存器 bank 和 operand collector 送入，tile 还要符合支持的 dtype 与布局。访存、发射、依赖、寄存器压力和 tile 几何都可能让计算管线吃不饱。",
        "The experiment compares a well-aligned BF16 GEMM with an awkward shape using the same approximate FLOP scale. It reports time and achieved throughput, then reads the GPU compute capability. A faster aligned case is evidence about these two library-dispatched shapes, not proof that one specific Tensor Core instruction executed; that claim would require a kernel or profiler trace.",
        "实验比较一个对齐良好的 BF16 GEMM 与一个尺寸略不规则的 GEMM，两者保持相近的计算规模，记录延迟和实际吞吐，并读取 GPU compute capability。即使对齐形状更快，也只能说明这两个库调度 shape 的差异；要证明执行了某条 Tensor Core 指令，还需要 kernel 或 profiler 证据。",
        ["An SM combines scheduling, storage, load/store, scalar/vector, and matrix resources.", "Tensor Core throughput depends on a supported instruction and a fed pipeline.", "Shape alignment is an empirical library contract, not a universal multiple copied from a blog."],
        ["SM 同时包含调度、存储、load/store、标量/向量与矩阵资源。", "Tensor Core 吞吐取决于受支持的指令以及持续供数。", "shape 对齐是需要实测的库契约，不是从文章里抄一个万能倍数。"],
        ["Predict which shape the library will execute more efficiently.", "List the path from L2 response to matrix operands.", "Name the evidence required to assert Tensor Core dispatch."],
        ["预测哪个 shape 会被库更高效地执行。", "列出从 L2 返回数据到矩阵操作数的路径。", "写出证明 Tensor Core dispatch 所需的证据。"],
        "Time aligned and awkward BF16 GEMMs with similar arithmetic scale.",
        "测量计算规模接近的对齐与非规则 BF16 GEMM。",
        "square dimensions aligned to common library tiles",
        "与常见库 tile 对齐的方形维度",
        "nearby awkward M/N/K dimensions",
        "相邻但不规则的 M/N/K 维度",
        "dtype, GPU, timing, warm-up, and approximate FLOP count",
        "dtype、GPU、计时、warm-up 与近似 FLOP 量",
        "median latency, achieved TFLOP/s, and throughput ratio",
        "中位延迟、实际 TFLOP/s 与吞吐比",
        "Both candidates call `torch.mm`, so the installed PyTorch/cuBLAS stack selects tactics. The code synchronizes with events and validates output shapes; it does not label internal instructions without a trace.",
        "两个候选都调用 `torch.mm`，由已安装的 PyTorch/cuBLAS 选择 tactic。代码用 Event 同步并校验输出 shape，不会在没有 trace 时给内部指令贴标签。",
        "Treat alignment as a measured performance variable and preserve the full shape/dtype/backend identity with every result.",
        "把对齐看作需要测量的性能变量，并随结果保留完整 shape、dtype 与 backend 身份。",
        "Library autotuning, clocks, workspace, and architecture can select different kernels. Awkward does not always mean slower, especially when the total work is smaller.",
        "库 autotuning、频率、workspace 与架构都可能改变 kernel 选择。不规则 shape 也不一定更慢，尤其当总工作量更小时。",
        "Capture an Nsight Compute instruction mix and sweep each dimension independently around several tile boundaries.",
        "用 Nsight Compute 采集指令混合，并在多个 tile 边界附近分别扫描 M、N、K。",
        "pytorch-gpu",
        [("Aligned median", "对齐形状中位延迟", "aligned_median_ms", "ms"), ("Awkward median", "非规则形状中位延迟", "awkward_median_ms", "ms"), ("Aligned throughput", "对齐形状吞吐", "aligned_tflops", "float"), ("Awkward throughput", "非规则形状吞吐", "awkward_tflops", "float"), ("Aligned/awkward ratio", "对齐/非规则吞吐比", "throughput_ratio", "ratio")],
        ["a100_whitepaper", "cuda_best"],
        [],
        'flowchart LR\n  A["warp scheduler"] --> B["scoreboard"]\n  B --> C["register banks"]\n  C --> D["operand collector"]\n  D --> E["Tensor Core MMA"]\n  E --> F["accumulator"]',
    ),
    L(
        6,
        "attention-io-tiling",
        "Attention Acceleration Is an IO Problem",
        "Attention 加速首先是 IO 问题",
        "If exact attention still performs the same mathematical operation, how can changing the schedule reduce memory and latency?",
        "精确 attention 的数学结果没有改变，为什么只重排执行顺序就能降低内存与延迟？",
        "Naive attention forms scores `QKᵀ`, applies softmax, then multiplies by `V`. The score/probability tensor grows with sequence length squared and may be written to and read from external memory. IO-aware attention tiles Q, K, and V through on-chip storage and maintains online softmax statistics, avoiding full materialization while preserving the exact operation up to floating-point order.",
        "朴素 attention 先形成 `QKᵀ`，再做 softmax 并乘以 `V`。score/probability 张量随序列长度平方增长，往往要写入并读回外部显存。IO-aware attention 把 Q、K、V 分块送入片上存储，并维护 online softmax 统计量，从而避免完整物化，在浮点顺序误差范围内保持同一数学操作。",
        "The notebook implements an explicit eager baseline and compares it with PyTorch scaled-dot-product attention. It records output error, CUDA-event latency, and peak allocated memory after resetting the allocator statistic for each route. PyTorch may choose among fused and math backends according to inputs and build, so the recorded evidence names the API and environment rather than claiming a specific FlashAttention kernel without backend diagnostics.",
        "Notebook 明确实现 eager baseline，并与 PyTorch scaled-dot-product attention 比较。每条路径都会重置 allocator peak，记录输出误差、CUDA Event 延迟和峰值 allocated memory。PyTorch 会根据输入与软件构建选择 fused 或 math backend，因此结果只声明 API 与环境；没有 backend 诊断时，不会擅自声称运行了某个 FlashAttention kernel。",
        ["The quadratic score tensor is an execution choice, not the final output shape.", "Tiling trades on-chip state and recomputation for fewer external reads/writes.", "Exact mathematics does not imply bitwise-identical floating-point evaluation order."],
        ["二次方规模的 score 张量是执行选择，不是最终输出 shape。", "tiling 用片上状态和少量重计算换取更少的外部读写。", "数学上精确不代表浮点计算顺序逐位相同。"],
        ["Predict the eager score tensor size for the frozen shape.", "Predict which route uses less peak allocated memory.", "Choose a numerical tolerance before reading the output error."],
        ["预测固定 shape 下 eager score 张量的大小。", "预测哪条路径的 peak allocated memory 更低。", "查看输出误差前先确定数值容差。"],
        "Compare explicit eager attention with PyTorch SDPA at one fixed BF16 shape.",
        "在固定 BF16 shape 下比较显式 eager attention 与 PyTorch SDPA。",
        "materialized scores, softmax probabilities, and output matmul",
        "显式物化 score、softmax probability，再计算输出",
        "`scaled_dot_product_attention` with backend chosen by PyTorch",
        "由 PyTorch 选择 backend 的 `scaled_dot_product_attention`",
        "Q/K/V tensors, scale, dtype, shape, warm-up, and repetitions",
        "Q/K/V 张量、scale、dtype、shape、warm-up 与重复次数",
        "score bytes, latency, peak allocated memory, and maximum output error",
        "score 字节数、延迟、峰值 allocated memory 与最大输出误差",
        "The eager function is intentionally readable. Separate measurement functions reset peak memory, execute one route, synchronize, and retain outputs for the error check. This distinguishes algorithmic intermediate size from allocator evidence.",
        "eager 函数刻意保持可读。两条测量路径分别重置峰值、执行、同步并保留输出用于误差检查，从而区分算法中间张量大小与 allocator 证据。",
        "Prefer the IO-aware route only when its numerical contract and supported shape are satisfied; fall back explicitly when backend or precision constraints reject it.",
        "只有在数值契约和 shape 支持都满足时才采用 IO-aware 路径；backend 或精度约束不满足时应显式回退。",
        "Allocator peak is not physical HBM traffic, and a single shape cannot establish scaling. Backend selection may change with PyTorch, driver, mask, dropout, dtype, or head dimension.",
        "allocator peak 不等于物理显存流量，单个 shape 也不能证明缩放规律。PyTorch、driver、mask、dropout、dtype 或 head dimension 都可能改变 backend。",
        "Sweep sequence length and causal/mask modes, record selected SDPA backend diagnostics, and profile DRAM bytes with Nsight Compute.",
        "扫描 sequence length、causal 与 mask 模式，记录 SDPA backend 诊断，再用 Nsight Compute 测量 DRAM 字节。",
        "pytorch-gpu",
        [("Eager score tensor", "Eager score 张量", "score_tensor_mib", "mib"), ("Eager median", "Eager 中位延迟", "eager_median_ms", "ms"), ("SDPA median", "SDPA 中位延迟", "sdpa_median_ms", "ms"), ("Eager peak memory", "Eager 峰值内存", "eager_peak_mib", "mib"), ("SDPA peak memory", "SDPA 峰值内存", "sdpa_peak_mib", "mib"), ("Max output error", "最大输出误差", "max_abs_error", "float")],
        ["flashattention", "torch_sdpa"],
        [],
        'flowchart LR\n  A["Q/K/V tiles"] --> B["QKᵀ tile"]\n  B --> C["online softmax state"]\n  C --> D["accumulate V tile"]\n  D -->|"next K/V tile"| B\n  D --> E["final output"]',
    ),
    L(
        7,
        "hbm-circuit-to-package",
        "From DRAM Cells to HBM Packaging",
        "从 DRAM 单元到 HBM 封装",
        "HBM cells are still DRAM, so where does high bandwidth actually come from?",
        "HBM 单元仍然是 DRAM，它的高带宽究竟从哪里来？",
        "HBM stacks DRAM dies and connects many signals through TSVs and microbumps to a base die and silicon interposer near the GPU package. The cell still stores charge and needs sense amplifiers, rows, banks, and refresh. The bandwidth gain comes primarily from a very wide, highly parallel interface and package integration—not from turning DRAM cells into SRAM.",
        "HBM 把多层 DRAM die 堆叠起来，通过 TSV、microbump、base die 和 silicon interposer，在封装内靠近 GPU 建立大量并行信号。存储单元仍靠电荷保存数据，仍需要感放、行、bank 与刷新。高带宽主要来自更宽、更并行的接口与封装集成，而不是把 DRAM 变成 SRAM。",
        "Theoretical interface bandwidth is `bus_width_bits × pin_rate / 8`. The notebook calculates that relationship and measures a large device-to-device copy on the available RTX 5090, which uses GDDR7 rather than HBM. This contrast is intentional: the equation generalizes, while the recorded GPU truthfully identifies its external-memory technology. Effective copy bandwidth includes both a read and a write in the reported byte accounting.",
        "理论接口带宽为 `总线位宽 × 每 pin 速率 / 8`。Notebook 先计算这条关系，再在 RTX 5090 上测量大张量 device-to-device copy；5090 使用的是 GDDR7，不是 HBM。这个对照是刻意的：带宽公式可以迁移，但实测环境必须如实标注外部显存技术。有效 copy 带宽按一次读取加一次写回统计字节。",
        ["HBM is external package memory, not an SM-local cache.", "TSVs and interposers create a wide path; banks provide internal parallelism.", "Theoretical interface bandwidth and achieved application bandwidth are different quantities."],
        ["HBM 是封装外部显存，不是 SM 本地缓存。", "TSV 与 interposer 建立宽通路，bank 提供内部并行。", "理论接口带宽和应用实测带宽是两个量。"],
        ["Trace one read from a cell array to the GPU memory controller.", "Calculate bandwidth for a 512-bit interface at 28 Gb/s per pin.", "Predict why a copy benchmark cannot reach the exact theoretical number."],
        ["追踪一次读取从 cell array 到 GPU memory controller 的路径。", "计算 512-bit、每 pin 28 Gb/s 接口的理论带宽。", "预测 copy benchmark 为什么达不到精确理论值。"],
        "Calculate width-based bandwidth and measure large CUDA device copies.",
        "计算宽接口理论带宽，并测量大规模 CUDA device copy。",
        "theoretical bandwidth from interface width and pin rate",
        "由接口宽度与 pin 速率计算的理论带宽",
        "RTX 5090 device-copy effective bandwidth",
        "RTX 5090 device copy 有效带宽",
        "tensor size, dtype, warm-up, repetitions, and event timing",
        "张量大小、dtype、warm-up、重复次数与 Event 计时",
        "theoretical GB/s, copy median, effective GB/s, and achieved/theoretical ratio",
        "理论 GB/s、copy 中位延迟、有效 GB/s 与理论占比",
        "A preallocated source and destination avoid allocator timing. `copy_` is repeated between CUDA events, and requested traffic counts source read plus destination write. The formula example matches the official 5090 interface fields but does not relabel GDDR7 as HBM.",
        "预先分配 source 和 destination，避免把 allocator 时间算入。`copy_` 在 CUDA Event 之间重复执行，请求流量按 source read 加 destination write 统计。公式示例对应 5090 官方接口字段，但不会把 GDDR7 写成 HBM。",
        "Use the wide-interface equation for a ceiling and a controlled benchmark for achieved bandwidth; always name the memory technology and traffic convention.",
        "用宽接口公式给出上限，用受控 benchmark 给出实际值；始终注明显存技术和字节统计口径。",
        "Copy engines, caches, clocks, thermals, tensor size, ECC, and byte-count conventions affect the ratio. HBM package details differ across products and generations.",
        "copy engine、cache、频率、温度、tensor 大小、ECC 与字节口径都会影响比例；不同产品和代际的 HBM 封装也不相同。",
        "Repeat with a streaming triad kernel and profiler DRAM counters, then compare an actual HBM GPU using the identical protocol.",
        "增加 streaming triad kernel 与 profiler DRAM counter，再用同一协议测量一块真实 HBM GPU。",
        "pytorch-gpu",
        [("Theoretical interface bandwidth", "理论接口带宽", "theoretical_gbps", "float"), ("Copy median", "Copy 中位延迟", "copy_median_ms", "ms"), ("Effective copy bandwidth", "有效 copy 带宽", "effective_copy_gbps", "float"), ("Achieved/theoretical", "实测/理论", "achieved_fraction", "percent")],
        ["hbm_package", "rtx5090"],
        [("assets/HBM_circuit_to_gpu_connection.png", "HBM circuit-to-package path", "HBM 从电路到封装路径"), ("assets/HBM_circuit_to_gpu_connection_A4_portrait.pdf", "Printable HBM diagram", "可打印 HBM 图")],
        'flowchart LR\n  A["1T1C arrays"] --> B["sense amps + banks"]\n  B --> C["HBM stack + base die"]\n  C --> D["TSV / microbump"]\n  D --> E["interposer"]\n  E --> F["GPU memory controller"]',
    ),
    L(
        8,
        "l2-slices-cache-locality",
        "Inside an L2 Slice: Tags, Banks, and Miss State",
        "L2 Slice 内部：Tag、Bank 与 Miss 状态",
        "An L2 cache is made from SRAM, so why is its behavior more than just a fast array?",
        "L2 cache 由 SRAM 构成，为什么它的行为不只是“更快的数组”？",
        "A cache slice combines tag arrays, comparators, data banks, replacement state, queues, and miss-status tracking. An address is split into offset, set, and tag; tags decide whether a line is present, banks provide parallel access, and MSHR-like state tracks outstanding misses until refill. Conflicts can arise from placement, ports, banks, queues, or downstream memory even when capacity looks sufficient.",
        "一个 cache slice 不只有 data SRAM，还包括 tag array、比较器、替换状态、队列和 miss-status tracking。地址被拆成 offset、set 与 tag；tag 判断 cache line 是否命中，bank 提供并行访问，MSHR 类状态记录尚未完成的 miss，直到 refill 返回。即使总容量足够，也可能因为映射、端口、bank、队列或下游显存产生冲突。",
        "The lab sweeps a large CUDA tensor with contiguous and increasingly sparse strides. It reports requested bandwidth per accessed element. This is a locality probe, not a direct L2-hit counter: changing stride changes useful bytes per transaction and cache-line reuse, while reduction work and compiler kernels remain involved. The conceptual diagram labels likely components without claiming a die-accurate NVIDIA implementation.",
        "实验用连续访问和逐渐增大的 stride 扫描大 CUDA 张量，按实际访问元素计算请求带宽。它是 locality probe，不是 L2 hit counter：stride 会改变每个 transaction 的有效字节和 cache line 复用，同时归约工作与编译器 kernel 仍然参与。概念图标出常见组件，但不声称是 NVIDIA 某芯片的 die-accurate 实现。",
        ["Tag lookup and data access are distinct operations.", "Banking increases service parallelism but does not remove finite ports or queues.", "A miss consumes state until refill; too many outstanding misses can backpressure requesters."],
        ["Tag lookup 与 data access 是两个不同操作。", "banking 提高服务并行度，但端口和队列仍然有限。", "miss 会占用状态直到 refill；未完成 miss 太多会对请求端形成反压。"],
        ["Split a sample byte address into offset, set, and tag.", "Predict requested bandwidth as stride grows.", "Explain why this experiment cannot directly report L2 hit rate."],
        ["把一个示例字节地址拆成 offset、set 与 tag。", "预测 stride 增大时请求带宽如何变化。", "解释为什么本实验不能直接给出 L2 hit rate。"],
        "Sweep CUDA access stride and retain a transparent address-decomposition example.",
        "扫描 CUDA 访问 stride，并保留透明的地址拆分示例。",
        "contiguous access over the tensor",
        "连续访问整个张量",
        "strides 2, 4, 8, 16, and 32",
        "stride 为 2、4、8、16、32 的访问",
        "source allocation, dtype, accessed-element accounting, and timing helper",
        "source allocation、dtype、访问元素计数与计时函数",
        "median latency, requested GB/s, address tag/set/offset",
        "中位延迟、请求 GB/s 与地址 tag/set/offset",
        "Each view is consumed by the same reduction expression. The code counts only useful values, prints the decomposition assumptions, and labels the result as a PyTorch locality probe rather than a cache-counter measurement.",
        "每个 view 都由同一个归约表达式消费。代码只统计有效值，并打印地址拆分假设；结果被标为 PyTorch locality probe，而不是 cache counter 测量。",
        "Use stride timing to form a cache hypothesis, then require hardware counters before attributing the result to L2 hits, sectors, or miss queues.",
        "用 stride 计时形成 cache 假设，再用硬件 counter 证明 L2 hit、sector 或 miss queue 归因。",
        "Reduction scheduling and lower element count at large stride complicate comparisons. Prefetching, cache state, and clock variation can also alter the curve.",
        "大 stride 下元素数更少，归约调度会干扰比较；prefetch、cache 初始状态与频率波动也会改变曲线。",
        "Profile L2 sectors, hit rate, and DRAM bytes for equal-work custom kernels while sweeping working-set size across cache capacity.",
        "对等工作量 custom kernel 采集 L2 sector、hit rate 与 DRAM 字节，并让 working set 跨越 cache 容量。",
        "pytorch-gpu",
        [("Contiguous median", "连续访问中位延迟", "stride_1.median_ms", "ms"), ("Contiguous requested bandwidth", "连续请求带宽", "stride_1.requested_gbps", "float"), ("Stride-8 requested bandwidth", "Stride-8 请求带宽", "stride_8.requested_gbps", "float"), ("Stride-32 requested bandwidth", "Stride-32 请求带宽", "stride_32.requested_gbps", "float"), ("Example cache set", "示例 cache set", "address_example.set", "int")],
        ["cuda_programming", "a100_whitepaper"],
        [("assets/L2_cache_slice_circuit_structure.png", "Conceptual L2 slice", "概念性 L2 slice"), ("assets/L2_cache_slice_circuit_structure_A4_portrait.pdf", "Printable L2 slice diagram", "可打印 L2 slice 图")],
        'flowchart LR\n  A["request address"] --> B["tag + set + offset"]\n  B --> C["tag compare"]\n  C -->|"hit"| D["banked data array"]\n  C -->|"miss"| E["miss-status entry"]\n  E --> F["memory refill"]\n  F --> D',
    ),
    L(
        9,
        "noc-routing-contention",
        "NoC Routing, Buffers, and Contention",
        "NoC 路由、缓冲与拥塞",
        "Why can on-chip data movement slow down even when every link is individually fast?",
        "每条片上链路都很快，为什么数据在芯片内部仍会堵塞？",
        "A Network-on-Chip connects SMs, L2 slices, controllers, and other units through routers and links. Packets are split into flits; routers buffer inputs, choose routes, arbitrate virtual channels and switches, then traverse crossbars and physical links. When several flows request the same output, the link capacity is shared and queues grow. Backpressure carries the consequence upstream.",
        "NoC 通过 router 与 link 连接 SM、L2 slice、memory controller 等单元。packet 被拆成 flit；router 依次完成输入缓冲、路由选择、virtual channel 与 switch arbitration、crossbar 传输和物理链路发送。多条 flow 同时争用同一输出时，链路容量被共享，队列增长，backpressure 再向上游传播。",
        "The notebook runs a deterministic discrete-time queue model. A balanced pattern spreads sources across destinations; a hotspot pattern targets one output. Offered traffic and per-link service stay fixed. Queue area, maximum queue, delivered flits, and latency expose the congestion mechanism. The model does not claim NVIDIA's private topology, router width, or arbitration policy.",
        "Notebook 运行一个确定性的离散时间排队模型。balanced pattern 把 source 分散到多个 destination；hotspot pattern 让它们集中争用同一输出。两者保持 offered traffic 与单链路服务能力不变，比较队列面积、最大队列、已交付 flit 与延迟。模型不会声称还原 NVIDIA 的私有拓扑、router 宽度或 arbitration policy。",
        ["Bandwidth is a property of a path and traffic pattern, not only one link.", "Buffers absorb bursts but cannot fix sustained oversubscription.", "Backpressure turns a local hotspot into upstream stalls."],
        ["带宽属于路径与流量模式，不只属于一条 link。", "buffer 可以吸收突发，但无法解决持续超额流量。", "backpressure 会把局部 hotspot 变成上游 stall。"],
        ["Predict which traffic pattern builds the longer queue.", "Explain why more buffering changes burst tolerance but not steady service rate.", "Name the hardware counters needed for a native claim."],
        ["预测哪种 traffic pattern 会形成更长队列。", "解释为什么增加 buffer 只改变突发容忍度，不改变稳定服务速率。", "写出进行原生 NoC 归因所需的硬件 counter。"],
        "Compare balanced and hotspot traffic in a bounded queue simulator.",
        "在有限队列模拟器中比较 balanced 与 hotspot traffic。",
        "four sources distributed across four outputs",
        "四个 source 分散到四个 output",
        "the same sources targeting one hotspot output",
        "相同 source 集中到一个热点 output",
        "arrival schedule, output service rate, ticks, and queue discipline",
        "到达计划、output 服务速率、tick 数与队列纪律",
        "delivered flits, mean/max queue, and mean latency",
        "已交付 flit、平均/最大队列与平均延迟",
        "The simulator records enqueue time for each flit, services one flit per output per tick, and drains after arrivals stop. Identical demand makes destination concentration the independent variable.",
        "模拟器记录每个 flit 的入队时间，每个 output 每 tick 服务一个 flit，并在停止到达后排空。相同需求量使 destination concentration 成为唯一自变量。",
        "Treat congestion as a traffic-placement problem; reduce hotspots or overlap before assuming a faster arithmetic unit will help.",
        "把拥塞看作流量与放置问题；应先减少 hotspot 或改善 overlap，再考虑增加算力是否有效。",
        "Real NoCs have multiple hops, routing adaptivity, priorities, virtual channels, credit delays, and topology-specific links. This model proves only the queueing invariant.",
        "真实 NoC 还包含多跳、自适应路由、优先级、virtual channel、credit 延迟和特定拓扑；本模型只证明排队机制。",
        "Build a mesh model with hop-dependent links, then compare its predictions with Nsight Compute fabric/L2/DRAM stall evidence for a controlled multi-SM kernel.",
        "加入带 hop 的 mesh 模型，再用受控多 SM kernel 的 fabric/L2/DRAM stall 证据检验预测。",
        "numerical-model",
        [("Balanced mean latency", "Balanced 平均延迟", "balanced.mean_latency_ticks", "float"), ("Hotspot mean latency", "Hotspot 平均延迟", "hotspot.mean_latency_ticks", "float"), ("Balanced max queue", "Balanced 最大队列", "balanced.max_queue", "int"), ("Hotspot max queue", "Hotspot 最大队列", "hotspot.max_queue", "int"), ("Latency ratio", "延迟比", "hotspot_latency_ratio", "ratio")],
        ["a100_whitepaper", "cuda_programming"],
        [("assets/NoC_on_chip_network_circuit_structure.png", "Conceptual NoC router and links", "概念性 NoC router 与 link"), ("assets/NoC_on_chip_network_circuit_structure_A4_portrait.pdf", "Printable NoC diagram", "可打印 NoC 图")],
        'flowchart LR\n  A["input flits"] --> B["input buffers / VCs"]\n  B --> C["route + switch arbitration"]\n  C --> D["crossbar"]\n  D --> E["physical link"]\n  E --> F["downstream router"]\n  F -->|"credits/backpressure"| B',
    ),
    L(
        10,
        "sm-resources-occupancy-banks",
        "SM Resources: Occupancy, Registers, and Banks",
        "SM 资源：Occupancy、寄存器与 Bank",
        "Does maximizing occupancy guarantee a fast kernel, and can shared-memory bank conflicts matter even when data stays on chip?",
        "occupancy 拉满就一定快吗？数据已经在片上时，shared-memory bank conflict 还会影响性能吗？",
        "An SM admits thread blocks only while registers, shared memory, warp slots, and block slots are available. Occupancy measures resident warps relative to a hardware maximum; it helps hide latency but does not guarantee useful instructions, coalescing, or balanced pipelines. Shared memory is partitioned into banks, so simultaneous warp addresses that map to the same bank may be serialized unless the access is a supported broadcast.",
        "SM 只有在寄存器、shared memory、warp slot 与 block slot 都有余额时才能接纳新的 block。occupancy 表示 resident warp 相对硬件上限的比例，有助于隐藏延迟，却不能保证指令有用、访存合并或管线均衡。shared memory 还被划分成 bank，同一 warp 的多个地址若映射到同一 bank，且不是受支持的 broadcast，就可能被串行处理。",
        "The lab reads CUDA device properties, evaluates an explicit resource-budget formula for several candidate kernels, and maps warp lanes to 32 illustrative banks for different strides. These are capacity and address models. They do not expose per-kernel register allocation or prove a native bank conflict; those require compiled kernel metadata and profiler counters.",
        "实验读取 CUDA 设备属性，用显式资源预算公式评估多个候选 kernel，并把 warp lane 在不同 stride 下映射到 32 个示意 bank。结果属于 capacity 与 address model，不会假装已经得到某个 kernel 的寄存器分配或原生 bank conflict；后者需要编译元数据与 profiler counter。",
        ["Occupancy is constrained by the tightest resident resource.", "Higher occupancy can trade against registers or shared-memory reuse.", "Bank conflict is an address-mapping property inside a warp."],
        ["occupancy 由最紧张的 resident resource 决定。", "更高 occupancy 可能以更少寄存器或 shared-memory 复用为代价。", "bank conflict 是 warp 内地址映射的属性。"],
        ["Predict which resource limits each candidate block.", "Predict the maximum bank multiplicity for strides 1, 2, and 32.", "Explain why 100% modeled occupancy is not a performance promise."],
        ["判断每个候选 block 被哪项资源限制。", "预测 stride 1、2、32 的最大 bank 重数。", "解释为什么模型中的 100% occupancy 不是性能承诺。"],
        "Compute resource-limited occupancy and shared-memory bank mappings.",
        "计算资源限制下的 occupancy 与 shared-memory bank 映射。",
        "moderate threads, registers, and shared memory per block",
        "每 block 使用中等 threads、registers 与 shared memory",
        "register-heavy, shared-heavy, and conflicting-stride cases",
        "register-heavy、shared-heavy 与冲突 stride 场景",
        "declared resource limits, 32-lane warp, and 32 illustrative banks",
        "显式资源上限、32-lane warp 与 32 个示意 bank",
        "resident blocks/warps, occupancy bound, and bank multiplicity",
        "resident block/warp、occupancy bound 与 bank 重数",
        "The calculation takes the minimum block limit from threads, registers, shared memory, and block slots. A separate mapping counts bank IDs for each stride. Both tables remain inspectable and architecture assumptions are printed.",
        "计算分别由 threads、registers、shared memory 与 block slot 得到 block 上限，再取最小值；另一张表统计不同 stride 的 bank ID。所有架构假设都会打印出来。",
        "Use occupancy and bank models to choose experiments, then accept an optimization only after native kernel timing and counters confirm the suspected limit.",
        "用 occupancy 与 bank model 选择实验；只有原生 kernel 计时和 counter 证实限制后，才接受优化。",
        "The model uses declared illustrative resource limits because PyTorch does not expose every SM scheduling field uniformly. Broadcast rules and bank width can change the naive multiplicity interpretation.",
        "模型使用显式教学资源上限，因为 PyTorch 不会统一暴露所有 SM 调度字段；broadcast 规则与 bank width 也可能改变简单重数解释。",
        "Compile two CUDA kernels with `-Xptxas -v`, record registers/shared memory, and profile achieved occupancy plus bank-conflict counters.",
        "编译两个 CUDA kernel，使用 `-Xptxas -v` 记录寄存器/shared memory，再采集 achieved occupancy 与 bank-conflict counter。",
        "capacity-model",
        [("Balanced occupancy bound", "Balanced occupancy 上限", "occupancy.balanced", "percent"), ("Register-heavy occupancy", "Register-heavy occupancy", "occupancy.register_heavy", "percent"), ("Shared-heavy occupancy", "Shared-heavy occupancy", "occupancy.shared_heavy", "percent"), ("Stride-1 bank multiplicity", "Stride-1 bank 重数", "bank_multiplicity.stride_1", "int"), ("Stride-32 bank multiplicity", "Stride-32 bank 重数", "bank_multiplicity.stride_32", "int")],
        ["cuda_best", "cuda_programming"],
        [("assets/SM_compute_partition_circuit_structure.png", "Conceptual SM compute partition", "概念性 SM 计算分区"), ("assets/NoC_and_SM_circuit_structures_A4_portrait.pdf", "Printable NoC and SM diagrams", "可打印 NoC 与 SM 图")],
        'flowchart LR\n  A["block request"] --> B["thread/warp slots"]\n  A --> C["register budget"]\n  A --> D["shared-memory budget"]\n  B --> E["resident blocks"]\n  C --> E\n  D --> E\n  E --> F["scheduler hides latency"]',
    ),
    L(
        11,
        "controllers-atomics-power-clock",
        "Controllers, Atomics, and the Power/Clock Envelope",
        "控制器、原子操作与功耗/频率包络",
        "Why can thousands of parallel updates collapse into a serialized hotspot, and what does that have to do with the rest of the chip?",
        "数千个并行更新为什么会坍缩成一个串行热点？这与芯片其他结构有什么关系？",
        "A complete GPU also needs memory controllers and PHYs, atomic/reduction paths, clock distribution, power delivery, error handling, and global control. Atomics preserve a read-modify-write contract when many threads target shared state. They are indispensable for some algorithms, but concentration on a few addresses creates serialization and fabric/cache pressure even while many execution lanes are available.",
        "完整 GPU 还需要 memory controller、PHY、atomic/reduction path、时钟分配、电源供给、错误处理与全局控制。atomic 在多个 thread 更新共享状态时维护 read-modify-write 契约，很多算法离不开它；但大量更新集中到少数地址会形成串行化，同时加重 fabric 与 cache 压力，即使执行 lane 仍有空闲。",
        "The notebook uses CUDA `scatter_add_` as an atomic-style workload. One candidate spreads updates across many bins; another concentrates them on a small hotspot set. Values, update count, dtype, timing, and reduction result stay fixed. The result shows PyTorch GPU behavior for this operation, not the location or exact design of a dedicated atomic unit. A separate first-order `CV²f` table connects activity to the finite power/clock envelope without claiming telemetry.",
        "Notebook 用 CUDA `scatter_add_` 构造 atomic-style 工作负载：一个候选把更新分散到大量 bin，另一个集中到少量 hotspot bin。values、update 数、dtype、计时与归约结果保持一致。结果只说明 PyTorch GPU 上该操作的行为，不会声称定位到某个专用 atomic unit。另一个一阶 `CV²f` 表用于连接活动率与有限功耗/频率包络，但不冒充遥测。",
        ["Controllers translate requests into external-memory commands and schedule parallel resources.", "Atomic correctness can impose serialization when addresses collide.", "Clock and power networks constrain all units even though CUDA presents logical concurrency."],
        ["控制器把请求转成外部显存命令并调度并行资源。", "atomic 为正确性付出的代价在地址碰撞时会表现为串行。", "CUDA 呈现逻辑并发，但时钟与供电网络仍约束所有单元。"],
        ["Predict which index distribution is slower.", "Explain why equal update counts can create different contention.", "Separate the timing evidence from the power-model evidence."],
        ["预测哪种 index 分布更慢。", "解释为什么相同 update 数会产生不同竞争。", "把计时证据与功耗模型证据分开。"],
        "Compare dispersed and hotspot CUDA scatter-add updates.",
        "比较分散与热点式 CUDA scatter-add 更新。",
        "indices distributed across a large output",
        "index 分散到较大的 output",
        "indices concentrated on a small set of bins",
        "index 集中到少量 bin",
        "update values/count, output size, dtype, warm-up, and event timing",
        "update value/count、output 大小、dtype、warm-up 与 Event 计时",
        "median latency, collision ratio, checksum, and slowdown",
        "中位延迟、碰撞率、checksum 与 slowdown",
        "Each repeat zeroes the destination before the timed scatter. The two index tensors contain the same number of updates, and checksums verify the same total contribution. Collision ratio is a workload property, not a hardware counter.",
        "每次计时前都清零 destination；两个 index 张量包含相同数量的 update，checksum 验证总贡献相同。collision ratio 是工作负载属性，不是硬件 counter。",
        "Reduce address concentration or perform hierarchical local reduction when contention dominates, but preserve the exact update semantics.",
        "竞争占主导时，应减少地址集中或采用分层局部归约，同时保持原始更新语义。",
        "`scatter_add_` kernel selection is version-dependent, and caches or internal aggregation may alter scaling. The power model is separate and illustrative.",
        "`scatter_add_` 的 kernel 选择依赖版本，cache 或内部聚合会改变缩放规律；功耗模型是独立的教学证据。",
        "Sweep bins and update skew, add a two-stage local-reduce candidate, and collect atomic/fabric stall plus board-power telemetry separately.",
        "扫描 bin 数与 update skew，加入两阶段 local-reduce candidate，并分别采集 atomic/fabric stall 与板级功耗遥测。",
        "pytorch-gpu",
        [("Dispersed median", "分散更新中位延迟", "dispersed_median_ms", "ms"), ("Hotspot median", "热点更新中位延迟", "hotspot_median_ms", "ms"), ("Hotspot slowdown", "热点 slowdown", "hotspot_slowdown", "ratio"), ("Dispersed collision ratio", "分散碰撞率", "dispersed_collision_ratio", "percent"), ("Hotspot collision ratio", "热点碰撞率", "hotspot_collision_ratio", "percent")],
        ["cuda_programming", "cuda_best"],
        [("assets/GPU_on_chip_structures_attention_acceleration.png", "Other on-chip structures", "其他关键片上结构"), ("assets/GPU_circuit_structures_from_L2_A4_landscape.pdf", "Four-page printable GPU circuit atlas", "四页可打印 GPU 电路图册")],
        'flowchart LR\n  A["SM updates"] --> B["L1/L2 + NoC"]\n  B --> C["atomic read-modify-write"]\n  C --> D["memory controller / PHY"]\n  E["clock + power delivery"] --> A\n  E --> B\n  E --> C',
    ),
    L(
        12,
        "cuda-execution-simt-divergence",
        "CUDA Execution: Grid, Block, Warp, and Divergence",
        "CUDA 执行模型：Grid、Block、Warp 与分支分歧",
        "A CUDA kernel launches thousands of threads; which parts are programming abstractions and which consequences are visible at warp execution?",
        "CUDA kernel 启动数千个 thread；哪些是编程抽象，哪些会在 warp 执行中产生真实后果？",
        "A kernel launch defines a grid of blocks; each block contains threads with indices and can use block-scoped shared memory and barriers. Hardware schedules threads in warps under SIMT execution. Threads retain independent state, but divergent control paths within a warp may require multiple path executions with different active masks. Blocks must remain independent unless a feature explicitly provides a wider synchronization scope.",
        "一次 kernel launch 定义由 block 组成的 grid，每个 block 包含带索引的 thread，并可使用 block-scope shared memory 与 barrier。硬件按 warp 在 SIMT 模式下调度 thread。thread 拥有独立状态，但同一 warp 内的控制流分歧可能需要用不同 active mask 分别执行多条路径。除非明确使用更宽的同步机制，否则 block 之间必须相互独立。",
        "The notebook maps a one-dimensional problem onto grids and blocks, then evaluates three branch patterns by counting active lanes per warp and path. Uniform, half-warp, and alternating predicates can have the same true/false totals but different active-mask shapes. The metric is a transparent divergence-efficiency model, not instruction-level timing; compilers may predicate, simplify, or otherwise transform real branches.",
        "Notebook 先把一维问题映射到 grid 与 block，再统计三种 branch pattern 在每个 warp、每条路径上的 active lane。uniform、half-warp 与 alternating predicate 可以有相同的 true/false 总数，却形成不同 active mask。这里的指标是透明的 divergence-efficiency model，不是指令级计时；真实编译器可能使用 predication、化简或其他变换。",
        ["Grid/block/thread is the software hierarchy; warp is a hardware scheduling unit.", "A barrier must be reached by the required participating threads.", "Divergence cost depends on executed paths, active masks, and compiler behavior—not branch count alone."],
        ["grid/block/thread 是软件层级，warp 是硬件调度单位。", "barrier 必须由要求参与的 thread 到达。", "分支代价取决于执行路径、active mask 与编译器行为，不只看 branch 数。"],
        ["Compute the grid size for a non-multiple problem length.", "Predict active masks for half-warp and alternating predicates.", "Explain why launch return time is not kernel completion time."],
        ["计算问题长度不是 block 整数倍时的 grid size。", "预测 half-warp 与 alternating predicate 的 active mask。", "解释为什么 launch 返回时间不等于 kernel 完成时间。"],
        "Map indices and compare three explicit warp branch masks.",
        "映射线程索引并比较三种显式 warp 分支 mask。",
        "uniform branch outcomes within each warp",
        "warp 内 branch outcome 一致",
        "half-warp and alternating outcomes",
        "half-warp 与交替 outcome",
        "problem size, block size, warp size, and two-path assumption",
        "问题规模、block size、warp size 与两路径假设",
        "grid size, tail lanes, active masks, and modeled lane efficiency",
        "grid size、tail lane、active mask 与 lane efficiency 模型",
        "The code builds lane masks directly, calculates useful lane-work divided by issued lane slots for both paths, and reports the tail block. No custom CUDA compiler is needed to inspect the invariant.",
        "代码直接构造 lane mask，按两条路径计算有效 lane 工作占发射 lane slot 的比例，并报告 tail block。理解这个不变量不需要 custom CUDA compiler。",
        "Use the SIMT model to spot risky control flow, then inspect generated code and native timing before rewriting a readable branch.",
        "先用 SIMT 模型识别高风险控制流，再检查生成代码和原生计时，之后才决定是否改写可读分支。",
        "The two-path model ignores instruction counts, reconvergence details, predication, memory divergence, and independent thread scheduling. It is not a speedup predictor.",
        "两路径模型省略了指令数、reconvergence、predication、访存分歧和 independent thread scheduling，不能直接预测加速比。",
        "Implement equivalent uniform and divergent CUDA kernels, inspect SASS branch/predicate instructions, and time them across path-cost ratios.",
        "实现等价的 uniform/divergent CUDA kernel，检查 SASS branch/predicate 指令，并扫描不同路径开销比例。",
        "numerical-model",
        [("Grid blocks", "Grid block 数", "grid_blocks", "int"), ("Tail active threads", "尾 block 活跃线程", "tail_active_threads", "int"), ("Uniform efficiency", "Uniform efficiency", "patterns.uniform", "percent"), ("Half-warp efficiency", "Half-warp efficiency", "patterns.half_warp", "percent"), ("Alternating efficiency", "Alternating efficiency", "patterns.alternating", "percent")],
        ["cuda_programming", "cuda_best"],
        [],
        'flowchart LR\n  A["kernel launch"] --> B["grid of blocks"]\n  B --> C["threads grouped into warps"]\n  C --> D["predicate mask"]\n  D --> E["execute path A"]\n  D --> F["execute path B"]\n  E --> G["reconverge"]\n  F --> G',
    ),
    L(
        13,
        "coalescing-strides-shared-memory",
        "Coalescing, Strides, and Shared-Memory Staging",
        "合并访存、Stride 与 Shared-Memory 暂存",
        "Two tensors contain the same number of values; why can copying a transposed view be slower than copying a contiguous tensor?",
        "两个张量包含相同数量的值，为什么复制转置 view 可能比复制连续张量更慢？",
        "Global memory requests from a warp are combined into transactions according to the address segments touched. Adjacent lanes accessing adjacent words tend to use transferred bytes efficiently; strided patterns may require more transactions for the same useful bytes. Shared memory can stage a tile and change access order, but it adds loads, stores, synchronization, capacity use, and possible bank conflicts.",
        "一个 warp 的 global-memory request 会根据所触及的地址 segment 合并成 transaction。相邻 lane 访问相邻 word 通常能更充分利用传输字节；strided pattern 可能为相同有效字节发起更多 transaction。shared memory 可以暂存 tile 并改变访问顺序，但也会增加 load/store、同步、容量占用和潜在 bank conflict。",
        "The lab copies a contiguous 2-D CUDA tensor and its non-contiguous transpose into fresh contiguous outputs. Both expose the same logical element count and dtype, so requested bytes match. CUDA-event time and effective bandwidth show the layout consequence through PyTorch's copy kernels. A direct hardware-transaction claim still requires global-load/store sector counters.",
        "实验把一个连续二维 CUDA tensor 及其非连续转置 view 分别复制到新的连续输出。两者逻辑元素数与 dtype 相同，请求字节完全一致。CUDA Event 延迟和有效带宽显示 PyTorch copy kernel 对布局的响应；要声称具体硬件 transaction 数，仍需 global load/store sector counter。",
        ["Coalescing is evaluated across addresses requested by a warp instruction.", "A view can change strides without changing logical shape or storage ownership.", "Shared-memory tiling is useful when it converts repeated or strided global access into reused, organized access."],
        ["coalescing 针对一个 warp 指令请求的地址集合判断。", "view 可以只改变 stride，而不改变逻辑 shape 或底层 storage 所有权。", "shared-memory tiling 的价值在于把重复或跨步 global access 转成可复用、有组织的访问。"],
        ["Predict the strides of a tensor and its transpose.", "Predict which copy has higher requested bandwidth.", "List the costs introduced by a shared-memory transpose tile."],
        ["预测原 tensor 与 transpose view 的 stride。", "预测哪种 copy 的请求带宽更高。", "列出 shared-memory transpose tile 带来的成本。"],
        "Copy equal-sized contiguous and transposed CUDA views.",
        "复制大小相同的连续与转置 CUDA view。",
        "contiguous source to contiguous destination",
        "连续 source 到连续 destination",
        "transposed non-contiguous view to contiguous destination",
        "转置后的非连续 view 到连续 destination",
        "logical elements, dtype, destination layout, warm-up, and event timing",
        "逻辑元素数、dtype、destination layout、warm-up 与 Event 计时",
        "source strides, median latency, effective GB/s, and slowdown",
        "source stride、中位延迟、有效 GB/s 与 slowdown",
        "Preallocated outputs avoid allocator timing. `copy_` consumes either the base tensor or its transpose, and checksums establish equivalent content after accounting for transpose order.",
        "预分配 output 避免 allocator 计时。`copy_` 分别消费 base tensor 或 transpose view，并在考虑转置顺序后校验内容等价。",
        "Fix global access order before adding arithmetic micro-optimizations; introduce shared memory only with an explicit reuse or reordering purpose.",
        "先修正 global access order，再考虑算术微优化；只有目标是复用或重排时才引入 shared memory。",
        "PyTorch may use specialized copy kernels, and cache state plus matrix dimensions affect results. Requested bandwidth does not equal physical bus traffic.",
        "PyTorch 可能使用专用 copy kernel，cache 状态与矩阵维度也会影响结果；请求带宽不等于物理总线流量。",
        "Write naive and tiled CUDA transpose kernels and compare global sectors, shared bank conflicts, and end-to-end bandwidth.",
        "实现 naive 与 tiled CUDA transpose kernel，比较 global sector、shared bank conflict 与端到端带宽。",
        "pytorch-gpu",
        [("Contiguous median", "连续 copy 中位延迟", "contiguous_median_ms", "ms"), ("Transposed median", "转置 copy 中位延迟", "transposed_median_ms", "ms"), ("Contiguous bandwidth", "连续 copy 带宽", "contiguous_gbps", "float"), ("Transposed bandwidth", "转置 copy 带宽", "transposed_gbps", "float"), ("Transposed slowdown", "转置 slowdown", "transposed_slowdown", "ratio")],
        ["cuda_programming", "cuda_best"],
        [],
        'flowchart LR\n  A["warp addresses"] --> B["32-byte segments"]\n  B --> C["global transactions"]\n  C --> D["shared-memory tile"]\n  D --> E["reordered/reused access"]\n  E --> F["coalesced output"]',
    ),
    L(
        14,
        "reductions-atomics-warp-primitives",
        "Reductions, Atomics, and Warp Primitives",
        "归约、原子操作与 Warp 原语",
        "When many values must become one result, which intermediate states should remain thread-local, warp-local, block-local, or global?",
        "大量值最终汇成一个结果时，哪些中间状态应该留在线程、warp、block 或全局范围？",
        "A reduction combines values through an associative operation. Efficient GPU reductions usually form a hierarchy: thread-local partials, warp exchange or shared memory, block results, and a final combination. Atomics can combine block results safely, but atomically updating one global accumulator for every input creates maximum contention. Warp shuffle primitives exchange register values without shared memory, provided the active mask is correct.",
        "归约通过结合操作把许多值合成一个结果。高效 GPU reduction 通常分层进行：thread-local partial、warp exchange 或 shared memory、block result，最后再合并。atomic 可以安全组合 block result，但如果每个输入都更新同一个全局 accumulator，就会形成最大竞争。warp shuffle 能在正确 active mask 下直接交换寄存器值，无需 shared memory。",
        "The notebook compares native `torch.sum` with `scatter_add_` routes that direct the same values into one bin or many bins. It verifies checksums and reports latency. This is not a custom shuffle implementation; it demonstrates why the number and concentration of global updates matter. The theory section then maps that observation onto a hierarchical reduction design.",
        "Notebook 比较原生 `torch.sum` 与两条 `scatter_add_` 路径：相同 values 分别写入一个 bin 或许多 bin。代码校验 checksum 并记录延迟。它不是 custom shuffle 实现，而是展示全局 update 数量与集中程度为什么重要；理论部分再把这个观察映射到分层 reduction 设计。",
        ["Synchronization scope should match the state being shared.", "Hierarchical partial reduction lowers the number of global updates.", "Warp primitives require a correct mask for participating lanes."],
        ["同步范围应与共享状态的范围一致。", "分层 partial reduction 可以减少 global update 数。", "warp primitive 必须使用正确的参与 lane mask。"],
        ["Predict the fastest route for one scalar sum.", "Predict how one-bin contention compares with many-bin scatter.", "Explain where a block barrier is required in a shared-memory tree."],
        ["预测得到一个标量 sum 的最快路径。", "比较 one-bin contention 与 many-bin scatter。", "说明 shared-memory tree 在哪里需要 block barrier。"],
        "Compare library reduction with concentrated and distributed atomic-style updates.",
        "比较库归约、集中式与分散式 atomic-style update。",
        "optimized `torch.sum` reduction",
        "优化过的 `torch.sum` reduction",
        "one-bin and many-bin `scatter_add_`",
        "one-bin 与 many-bin `scatter_add_`",
        "values, dtype, element count, warm-up, and timing",
        "values、dtype、元素数、warm-up 与计时方式",
        "median latency, checksums, and slowdown versus library reduction",
        "中位延迟、checksum 与相对库归约的 slowdown",
        "Each candidate consumes the same source tensor. The scatter routes allocate destination buffers before timing and clear them per repeat. Output sums are checked within a floating-point tolerance.",
        "每个候选消费同一个 source tensor。scatter 路径在计时前分配 destination，每次重复前清零，并在浮点容差内检查 output sum。",
        "Start from a trusted library reduction; write a custom hierarchical kernel only when shape, fusion, or output structure justifies it and correctness has an oracle.",
        "优先使用可信的库归约；只有 shape、fusion 或输出结构确实需要时才写 custom hierarchical kernel，并保留正确性 oracle。",
        "Different kernels may accumulate in different orders, so bitwise output equality is not expected. Scatter is a mechanism probe, not a fair replacement for every reduction.",
        "不同 kernel 的累加顺序可能不同，因此不能要求逐位相等；scatter 是机制 probe，不是所有 reduction 的公平替代。",
        "Implement warp-shuffle and shared-memory block reductions, sweep block sizes, and inspect synchronization plus atomic counters.",
        "实现 warp-shuffle 与 shared-memory block reduction，扫描 block size，并检查同步与 atomic counter。",
        "pytorch-gpu",
        [("Library sum median", "库 sum 中位延迟", "sum_median_ms", "ms"), ("One-bin median", "One-bin 中位延迟", "one_bin_median_ms", "ms"), ("Many-bin median", "Many-bin 中位延迟", "many_bin_median_ms", "ms"), ("One-bin slowdown", "One-bin slowdown", "one_bin_slowdown", "ratio"), ("Checksum error", "Checksum 误差", "checksum_error", "float")],
        ["cuda_programming", "cuda_best"],
        [],
        'flowchart LR\n  A["thread-local partials"] --> B["warp reduction"]\n  B --> C["block shared state"]\n  C --> D["one partial per block"]\n  D --> E["final reduction / bounded atomics"]',
    ),
    L(
        15,
        "events-streams-library-baselines",
        "CUDA Events, Streams, and Library Baselines",
        "CUDA Event、Stream 与库基线",
        "Why can a host timer report an almost-free GPU operation that clearly takes milliseconds to finish?",
        "一个 GPU 操作明明要运行若干毫秒，为什么 host timer 却可能显示几乎免费？",
        "Kernel launches and many CUDA operations are asynchronous with respect to the host. A host timer around enqueue calls often measures submission overhead; a device event recorded in the same stream measures elapsed device work after synchronization. Streams are ordered queues. Multiple streams express potential concurrency, but overlap occurs only when dependencies, engines, and resources allow it.",
        "kernel launch 与许多 CUDA 操作相对 host 是异步的。只在 enqueue 调用外包一层 host timer，通常测到的是提交开销；在同一 stream 中记录 CUDA Event 并同步，才能测量 device work 的经过时间。stream 是有序工作队列，多 stream 只是表达潜在并发，只有依赖、engine 与资源都允许时才会重叠。",
        "The notebook times the same BF16 GEMM in two ways: unsynchronized host enqueue time and synchronized CUDA events. It also reports achieved library GEMM throughput. The gap demonstrates the timing protocol error. The lesson does not promise multi-stream speedup; it provides a dependency checklist before readers add pinned-memory copies or independent kernels.",
        "Notebook 用两种方式测量同一个 BF16 GEMM：未同步的 host enqueue time，以及同步后的 CUDA Event 时间；同时报告库 GEMM 吞吐。两者差距直接暴露计时协议错误。本课不会承诺 multi-stream 必然加速，而是先给出依赖检查表，再让读者增加 pinned-memory copy 或独立 kernel。",
        ["Enqueue completion is not device completion.", "Operations in one stream are ordered; different streams need explicit dependencies for correctness.", "A library baseline establishes the cost of replacing a mature implementation."],
        ["enqueue 完成不等于 device 完成。", "同一 stream 内操作有序；不同 stream 的正确性依赖必须显式表达。", "库基线决定了替换成熟实现所要跨越的性能门槛。"],
        ["Predict the host enqueue/event-time ratio.", "Explain why a synchronization belongs after the stop event.", "List the conditions needed for copy/compute overlap."],
        ["预测 host enqueue 与 Event 时间的比例。", "解释为什么同步要放在 stop event 之后。", "列出 copy/compute overlap 所需条件。"],
        "Compare an unsynchronized host timer with CUDA-event timing for one GEMM.",
        "对同一 GEMM 比较未同步 host timer 与 CUDA Event 计时。",
        "host wall time around asynchronous enqueue",
        "异步 enqueue 外层的 host wall time",
        "CUDA events around completed device execution",
        "包围完整 device execution 的 CUDA Event",
        "operation, shape, dtype, stream, warm-up, and repetitions",
        "operation、shape、dtype、stream、warm-up 与重复次数",
        "enqueue microseconds, event milliseconds, timing illusion ratio, and TFLOP/s",
        "enqueue 微秒、Event 毫秒、计时错觉比例与 TFLOP/s",
        "The host loop deliberately omits synchronization until after all enqueue samples, while the event helper records start/stop per repeat and synchronizes the stop event. A final checksum keeps the operation live.",
        "host loop 刻意在全部 enqueue sample 之后才同步；Event helper 则每次记录 start/stop 并同步 stop event。最终 checksum 保证操作没有被无效化。",
        "Use CUDA events or profiler timelines for device latency and keep host/service latency as a separately named metric.",
        "device latency 使用 CUDA Event 或 profiler timeline；host/service latency 必须作为另一个明确命名的指标。",
        "Events measure work in their stream context, and unrelated work can interfere. Host timers are valid for synchronized end-to-end questions, so the lesson is about matching timer to question—not banning host time.",
        "Event 测量的是其 stream 上下文中的工作，也可能受无关任务干扰。host timer 对同步后的端到端问题仍然有效，关键是让计时器匹配问题。",
        "Build a double-buffered pinned-memory pipeline, verify dependencies with events, and inspect actual copy/compute overlap on a profiler timeline.",
        "构建 double-buffered pinned-memory pipeline，用 Event 验证依赖，并在 profiler timeline 上检查真实 copy/compute overlap。",
        "pytorch-gpu",
        [("Host enqueue median", "Host enqueue 中位值", "host_enqueue_us", "float"), ("CUDA event median", "CUDA Event 中位值", "event_median_ms", "ms"), ("Timing illusion ratio", "计时错觉倍数", "timing_illusion_ratio", "ratio"), ("Library GEMM throughput", "库 GEMM 吞吐", "library_tflops", "float")],
        ["torch_cuda", "cuda_programming"],
        [],
        'flowchart LR\n  A["host enqueue"] --> B["stream work queue"]\n  B --> C["start event"]\n  C --> D["GPU operation"]\n  D --> E["stop event"]\n  E --> F["synchronize + elapsed time"]',
    ),
    L(
        16,
        "performance-evidence-portfolio",
        "From Kernel Evidence to Inference Engineering",
        "从 Kernel 证据到推理工程",
        "What makes a GPU optimization result useful beyond one notebook—and what evidence demonstrates inference-engineering skill?",
        "一个 GPU 优化结果怎样才能走出单个 notebook？什么样的证据能真正体现推理工程能力？",
        "CUDA operator work and LLM inference engineering overlap but are not identical. Kernel work emphasizes memory access, instruction selection, tiling, occupancy, and correctness. Inference work additionally covers model phases, batching, KV state, APIs, observability, capacity, and release decisions. A strong project connects a bottleneck hypothesis to code, controlled measurement, model/service impact, and a rollback gate.",
        "CUDA 算子与大模型推理工程有交集，但并不等同。kernel 工作更关注访存、指令选择、tiling、occupancy 与正确性；推理工程还要覆盖模型阶段、batching、KV state、API、可观测性、容量与发布决策。高质量项目应把瓶颈假设、代码、受控测量、模型/服务影响和 rollback gate 连起来。",
        "The lab audits the first fifteen Chapter 04 artifacts as an evidence portfolio. It counts complete environment identities, evidence labels, metrics, analyses, and conclusions, then maps lessons to hardware, kernel, and inference layers. This is executable quality control rather than a salary forecast or job-market claim. Missing artifacts remain visible as missing instead of being filled with invented results.",
        "实验把第四章前 15 课 artifact 当成一个 evidence portfolio 做审计，统计环境身份、证据标签、metrics、analysis 与 conclusion 是否完整，再把课程映射到 hardware、kernel 和 inference 三层。它是可执行的质量控制，不预测薪资或招聘市场；缺少的 artifact 会如实显示缺失，不会补造结果。",
        ["A microbenchmark is stronger when it names the system decision it informs.", "Evidence must preserve environment, workload, comparison, and boundary.", "Inference engineering spans operator, runtime, service, and release layers."],
        ["microbenchmark 只有明确服务于哪个系统决策时才更有价值。", "证据必须保留环境、工作负载、比较条件与边界。", "推理工程跨越算子、runtime、service 与 release 多个层次。"],
        ["Predict how many earlier lessons have complete artifacts after a full run.", "Classify one lesson as hardware model, kernel measurement, or systems decision.", "Write the decision that your strongest benchmark supports."],
        ["预测完整运行后有多少前置课程具备完整 artifact。", "把一课归类为 hardware model、kernel measurement 或 systems decision。", "写出你最强 benchmark 所支持的决策。"],
        "Audit the preceding structured artifacts and build an evidence-coverage matrix.",
        "审计前置结构化 artifact，并生成证据覆盖矩阵。",
        "a list of lesson titles without machine-readable evidence",
        "只有课程标题、没有机器可读证据的列表",
        "the executed artifacts for Lessons 01–15",
        "第 01–15 课执行后的 artifact",
        "required artifact fields and fixed lesson-layer mapping",
        "artifact 必需字段与固定课程层级映射",
        "artifact completeness, evidence-label coverage, and layer coverage",
        "artifact 完整率、evidence label 覆盖与层级覆盖",
        "The code walks sibling lesson directories, validates a minimal schema, counts evidence classes, and prints missing fields. It never edits earlier evidence or treats file existence as proof that a conclusion is correct.",
        "代码遍历相邻课程目录，验证最小 schema，统计 evidence class 并打印缺失字段。它不会修改前置证据，也不会把文件存在等同于结论正确。",
        "Present performance work as a chain from mechanism to reproducible evidence to a bounded system decision.",
        "把性能工作组织成从机制、可复现实证到有边界系统决策的一条链。",
        "Schema completeness cannot detect a flawed experiment or unsupported interpretation. Human review, reproduction, and profiler evidence remain necessary.",
        "schema 完整不能发现实验设计错误或不受支持的解释，仍然需要人工审阅、复现与 profiler 证据。",
        "Add a review rubric for causal controls, correctness tolerance, profiler trace, end-to-end impact, and rollback rehearsal; score one portfolio item manually.",
        "增加因果控制、正确性容差、profiler trace、端到端影响与 rollback rehearsal 的审阅 rubric，并人工评审一个项目。",
        "compatibility-probe",
        [("Artifacts found", "找到的 artifact", "artifacts_found", "int"), ("Complete artifacts", "完整 artifact", "complete_artifacts", "int"), ("Completion rate", "完整率", "completion_rate", "percent"), ("Evidence labels represented", "覆盖的证据标签", "evidence_labels_represented", "int"), ("Portfolio layers represented", "覆盖的项目层级", "layers_represented", "int")],
        ["cuda_best", "roofline"],
        [],
        'flowchart LR\n  A["hardware mechanism"] --> B["kernel hypothesis"]\n  B --> C["controlled measurement"]\n  C --> D["model/service impact"]\n  D --> E["acceptance + rollback decision"]\n  E --> F["reproducible portfolio evidence"]',
    ),
    L(
        17,
        "gpu-spec-table-audit",
        "Reading GPU Specification Tables Critically",
        "审慎阅读 GPU 参数表",
        "Can one TFLOPS, TOPS, memory-capacity, or bandwidth number tell you which GPU is faster for an LLM workload?",
        "一个 TFLOPS、TOPS、显存容量或带宽数字，能直接说明哪块 GPU 更适合 LLM 吗？",
        "A specification only has meaning with its precision, dense/sparse convention, clock basis, form factor, memory technology, and workload connection. Capacity answers whether state may fit; bandwidth constrains low-intensity traffic; compute throughput constrains sufficiently high-intensity work; interconnect matters only when communication crosses devices. Marketing AI TOPS and a specific dense BF16 workload are not automatically comparable.",
        "参数只有连同精度、dense/sparse 口径、频率基础、形态、显存技术与工作负载一起才有意义。容量回答状态能否放下，带宽约束低强度流量，算力约束足够高强度的计算，互联只在通信跨设备时起作用。营销口径的 AI TOPS 不能自动映射到某个 dense BF16 工作负载。",
        "The notebook audits a frozen official RTX 5090 fact set: 32 GB GDDR7, 512-bit interface, 1792 GB/s bandwidth, and compute capability 12.0. It verifies the width/rate bandwidth arithmetic, compares reported device capacity, imports the measured copy result from Lesson 07, and computes illustrative Roofline ceilings across arithmetic intensities. The supplied quick-table image is treated as an audit exercise; every value should be rechecked against a product page or architecture guide before use.",
        "Notebook 审计一组固定的 RTX 5090 官方事实：32 GB GDDR7、512-bit 接口、1792 GB/s 带宽和 compute capability 12.0。代码验证宽度/速率带宽公式，对照设备实测容量，引入第 07 课 copy 结果，并计算多种算术强度下的示意 Roofline 上限。素材中的参数速查图只作为审计练习；任何数值在使用前都要回到产品页或架构指南复核。",
        ["A number without precision and sparsity convention is incomplete.", "Capacity, bandwidth, compute, and interconnect constrain different workload regimes.", "Official theoretical specifications and empirical application results must remain separate columns."],
        ["没有精度与稀疏口径的数字是不完整的。", "容量、带宽、算力与互联约束不同工作负载区间。", "官方理论参数与应用实测结果必须分列。"],
        ["Classify each table field as capacity, bandwidth, compute, or connectivity.", "Verify the 1792 GB/s arithmetic from width and pin rate.", "Predict the Roofline ceiling at low versus high arithmetic intensity."],
        ["把表中字段分类为容量、带宽、算力或连接。", "用位宽与 pin 速率复核 1792 GB/s。", "预测低、高算术强度下的 Roofline 上限。"],
        "Audit official fields, empirical device facts, and a measured copy result.",
        "审计官方字段、设备实测事实与 copy 实验结果。",
        "an unlabeled screenshot treated as authoritative",
        "把无口径截图直接当作权威参数",
        "source-tagged fields plus arithmetic and environment checks",
        "带来源字段、公式复核与环境检查",
        "official fact snapshot, unit conventions, and recorded GPU",
        "官方事实快照、单位口径与实测 GPU",
        "capacity agreement, bandwidth formula error, achieved ratio, and Roofline ceilings",
        "容量一致性、带宽公式误差、实测占比与 Roofline 上限",
        "A source dictionary carries units and URLs. Assertions catch bandwidth arithmetic or memory-technology drift. The Roofline table labels its compute roof as illustrative rather than substituting AI TOPS for a specific precision peak.",
        "source dictionary 连同单位和 URL 一起保存；assertion 检查带宽公式或显存技术是否漂移。Roofline 表将 compute roof 明确标为示意值，不会用 AI TOPS 冒充某精度峰值。",
        "Choose hardware from a workload sheet that combines capacity, arithmetic intensity, latency/throughput targets, supported software, and measured evidence.",
        "用同时包含容量、算术强度、延迟/吞吐目标、软件支持与实测证据的 workload sheet 选择硬件。",
        "Product pages can change, board variants differ, and theoretical peaks are not guaranteed. The checked-in snapshot must be revalidated for procurement or publication decisions.",
        "产品页会更新，不同板卡变体也可能不同，理论峰值更不等于保证值；用于采购或发表前必须重新校准本章快照。",
        "Create a comparison sheet for two candidate GPUs using one frozen workload, then run the same memory and GEMM probes on both.",
        "针对一个固定 workload 建立两块候选 GPU 的对比表，再在两者上运行相同 memory 与 GEMM probe。",
        "capacity-model",
        [("Reported device memory", "设备报告显存", "device_memory_gib", "float"), ("Official capacity", "官方容量", "official_memory_gib", "float"), ("Bandwidth formula error", "带宽公式误差", "bandwidth_formula_error", "percent"), ("Lesson 07 achieved fraction", "第 07 课实测占比", "lesson07_achieved_fraction", "percent"), ("Fields with explicit units", "具有明确单位的字段", "fields_with_units", "int")],
        ["rtx5090", "roofline"],
        [("assets/NVIDIA_GPU_parameter_quick_table.png", "GPU parameter quick table to audit", "待审计的 GPU 参数速查表")],
        'flowchart LR\n  A["workload shape + precision"] --> B["capacity check"]\n  A --> C["arithmetic intensity"]\n  C --> D["bandwidth roof"]\n  C --> E["compute roof"]\n  A --> F["software + interconnect support"]\n  B --> G["measured candidate"]\n  D --> G\n  E --> G\n  F --> G',
    ),
]


# Lesson 16 retains the role-spectrum material from the study notes without freezing
# short-lived compensation claims into a technical chapter.
LESSONS[15]["extra_en"] = r'''
### Role spectrum and evidence

| Role emphasis | Main object of work | Strong project evidence |
|---|---|---|
| CUDA / kernel performance | instruction, tile, memory access, launch shape | correctness oracle, profiler trace, latency distribution, dispatch proof |
| Inference-engine optimization | Prefill/Decode, KV state, batching, runtime integration | phase metrics, memory budget, backend comparison, failure and rollback gate |
| ML systems | compiler, distributed execution, data/model pipeline | end-to-end bottleneck isolation, scale curve, observability, reproducible environment |
| Model algorithm | objective, architecture, data, quality | task metric, ablation, generalization and error analysis |

A dual-stack engineer does not need to claim equal depth everywhere. A useful profile has
one deep axis—such as CUDA kernels or inference runtimes—and enough adjacent model and
service knowledge to connect a local optimization to user-visible behavior. Current job
titles and compensation are market data, not GPU invariants; evaluate them from dated job
postings with location, level, company type, and total-compensation fields kept separate.
'''.strip()

LESSONS[15]["extra_zh"] = r'''
### 岗位光谱与证据

| 岗位侧重点 | 主要工作对象 | 有说服力的项目证据 |
|---|---|---|
| CUDA / kernel 性能 | 指令、tile、访存、launch shape | 正确性 oracle、profiler trace、延迟分布、dispatch 证据 |
| 推理引擎优化 | Prefill/Decode、KV state、batching、runtime 集成 | 分阶段指标、内存预算、backend 对照、失效与 rollback gate |
| ML systems | 编译器、分布式执行、数据/模型流水线 | 端到端瓶颈定位、扩展曲线、可观测性、可复现环境 |
| 模型算法 | 目标函数、架构、数据、质量 | 任务指标、ablation、泛化与错误分析 |

双栈并不意味着每个方向都要声称同样深。更实际的能力结构是先选择一个深轴，例如 CUDA kernel 或推理 runtime，再补足相邻的模型与服务知识，把局部优化连接到用户可见结果。岗位名称与薪酬属于会变化的市场数据，不是 GPU 不变量；若要比较，应使用带日期的招聘信息，并分开记录地区、级别、公司类型与总包口径。
'''.strip()
