#!/usr/bin/env python3
"""Original bilingual curriculum data for Chapter 05."""

from __future__ import annotations


COMMON_REFS = {
    "tutorials": ("Triton tutorials", "https://triton-lang.org/main/getting-started/tutorials/"),
    "vector": ("Triton vector addition tutorial", "https://triton-lang.org/main/getting-started/tutorials/01-vector-add.html"),
    "softmax": ("Triton fused softmax tutorial", "https://triton-lang.org/main/getting-started/tutorials/02-fused-softmax.html"),
    "matmul": ("Triton matrix multiplication tutorial", "https://triton-lang.org/main/getting-started/tutorials/03-matrix-multiplication.html"),
    "layernorm": ("Triton LayerNorm tutorial", "https://triton-lang.org/main/getting-started/tutorials/05-layer-norm.html"),
    "attention": ("Triton fused attention tutorial", "https://triton-lang.org/main/getting-started/tutorials/06-fused-attention.html"),
    "debug": ("Debugging Triton", "https://triton-lang.org/main/programming-guide/chapter-3/debugging.html"),
    "api": ("Triton Python API", "https://triton-lang.org/main/python-api/triton.html"),
    "cuda": ("CUDA C++ Programming Guide", "https://docs.nvidia.com/cuda/cuda-c-programming-guide/"),
    "best": ("CUDA C++ Best Practices Guide", "https://docs.nvidia.com/cuda/cuda-c-best-practices-guide/"),
    "pytorch_compile": ("torch.compile documentation", "https://docs.pytorch.org/docs/stable/generated/torch.compile.html"),
    "sdpa": ("PyTorch scaled dot product attention", "https://docs.pytorch.org/docs/stable/generated/torch.nn.functional.scaled_dot_product_attention.html"),
    "cutlass": ("NVIDIA CUTLASS documentation", "https://docs.nvidia.com/cutlass/"),
}


def lesson(no, slug, title_en, title_zh, concept_en, concept_zh, mechanism_en,
           mechanism_zh, risk_en, risk_zh, experiment_en, experiment_zh,
           conclusion_en, conclusion_zh, primary_en, primary_zh, primary_kind,
           secondary_en, secondary_zh, secondary_kind, refs,
           evidence="native-backend"):
    return {
        "no": no, "slug": slug, "title_en": title_en, "title_zh": title_zh,
        "concept_en": concept_en, "concept_zh": concept_zh,
        "mechanism_en": mechanism_en, "mechanism_zh": mechanism_zh,
        "risk_en": risk_en, "risk_zh": risk_zh,
        "experiment_en": experiment_en, "experiment_zh": experiment_zh,
        "conclusion_en": conclusion_en, "conclusion_zh": conclusion_zh,
        "result_fields": [
            (primary_en, primary_zh, "primary", primary_kind),
            (secondary_en, secondary_zh, "secondary", secondary_kind),
            ("Maximum absolute error", "最大绝对误差", "max_abs_error", "scientific"),
            ("Acceptance gate", "验收 gate", "passed", "bool"),
        ],
        "refs": refs, "evidence_label": evidence,
    }


LESSONS = [
lesson(1, "operator-boundaries", "Operator Boundaries and the Cost of Small Kernels",
"算子边界与小 kernel 的真实成本", "fusion, launch count, and memory traffic", "融合、launch 数与显存流量",
"An eager expression may read and write a full tensor at every operator boundary. A Triton program can keep the intermediate value in registers and store once. The useful comparison therefore freezes the algebra and separates launch count, requested bytes, and latency.",
"eager 表达式可能在每个算子边界都完整读写 tensor。Triton program 可以让中间值停留在寄存器中，只写回一次。因此实验固定代数表达式，并把 launch 数、请求字节与延迟分开。",
"A faster fused kernel does not prove every operator should be rewritten. Very small inputs, compiler fusion, or a strong library kernel can erase the advantage.",
"融合 kernel 更快，不代表所有算子都该重写。输入很小、编译器已融合，或库函数足够强时，优势可能消失。",
"Compare one Triton affine kernel with the equivalent two-operation eager PyTorch CUDA path on the same tensor.",
"在同一 tensor 上，对比一个 Triton affine kernel 与等价的两步 eager PyTorch CUDA 路径。",
"Fuse only after measurements show that intermediate traffic or launch overhead matters for the production shape.",
"只有实测表明中间流量或 launch overhead 影响目标 shape 时，才把融合纳入交付。",
"Triton median", "Triton 中位延迟", "ms", "PyTorch eager median", "PyTorch eager 中位延迟", "ms", ["vector","best"]),

lesson(2, "programming-models", "Blocked Programs versus CUDA Threads", "Blocked program 与 CUDA thread",
"program_id, blocked tensors, and scalar threads", "program_id、blocked tensor 与标量 thread",
"CUDA exposes scalar threads grouped into blocks. Triton exposes a grid of program instances; each instance evaluates tensor expressions such as tl.arange. The mapping can resemble one CUDA block, but it is a reasoning aid rather than an identity.",
"CUDA 暴露的是按 block 组织的标量 thread；Triton 暴露 program instance 的 grid，每个 instance 计算 tl.arange 一类 tensor 表达式。它可以近似类比一个 CUDA block，但不能把二者视为完全等同。",
"Treating each lane of a blocked tensor as an independently scheduled CUDA thread leads to wrong assumptions about synchronization and storage.",
"把 blocked tensor 的每个 lane 当成独立调度的 CUDA thread，会对同步与存储做出错误假设。",
"Implement vector addition with 256 elements per Triton program and compare it with torch.add.",
"让每个 Triton program 处理 256 个元素，并与 torch.add 对照。",
"Reason in blocked programs first; descend to warp and instruction details only when generated code or counters require it.",
"先用 blocked program 推理；只有生成代码或 counter 提出问题时，再下钻到 warp 与指令。",
"Triton median", "Triton 中位延迟", "ms", "torch.add median", "torch.add 中位延迟", "ms", ["vector","cuda"]),

lesson(3, "reproducible-baseline", "Version Identity and a Reproducible Baseline", "版本身份与可复现实验基线",
"JIT cache, target identity, and cold versus warm time", "JIT cache、目标身份与冷暖时间",
"Triton performance depends on the Python package, compiler pipeline, backend target, driver-facing runtime, input specialization, and cache state. The GPU name alone is not an experiment identity. Cold host time and warm event time must remain separate fields.",
"Triton 性能同时受 Python package、编译流水线、backend target、driver/runtime、输入特化和 cache 状态影响。只记录 GPU 名称不构成实验身份；冷启动主机时间与 warm event 时间必须分列。",
"The CUDA version printed by nvidia-smi is a driver capability signal, not proof of the Toolkit or compiler used by the kernel.",
"nvidia-smi 显示的 CUDA Version 是 driver capability 信号，不等于本地 Toolkit 或 kernel 编译器版本。",
"Record the complete environment and measure the first host-observed launch separately from warm GPU-event samples.",
"记录完整环境，并把首次主机观察调用与 warm GPU-event 样本分开测量。",
"A benchmark is reusable only when target, versions, shapes, dtype, cache state, and timing boundary are visible.",
"只有 target、版本、shape、dtype、cache 状态和计时边界都可见时，benchmark 才能复用。",
"First host call", "首次主机调用", "ms", "Warm GPU median", "Warm GPU 中位延迟", "ms", ["api","best"]),

lesson(4, "first-vector-kernel", "A Tail-Safe Vector Kernel", "第一个 tail-safe 向量 kernel",
"program_id, tl.arange, mask, and BLOCK", "program_id、tl.arange、mask 与 BLOCK",
"A vector kernel derives offsets from program_id and a compile-time BLOCK. The runtime element count controls a tail mask, while BLOCK shapes the compiler-visible tensor. Correctness at non-divisible lengths is part of the kernel contract.",
"向量 kernel 用 program_id 和编译期 BLOCK 推导 offset；运行期元素数控制 tail mask，BLOCK 则决定编译器看到的 tensor 形状。不能整除的长度也是 kernel contract 的一部分。",
"Omitting the load and store mask may appear correct on aligned examples while reading or writing beyond the allocation on the first awkward shape.",
"省略 load/store mask 可能在对齐样例上看似正确，却会在第一个非对齐 shape 上越界。",
"Sweep four BLOCK values on an odd vector length and verify every tail element.",
"在奇数长度向量上 sweep 四个 BLOCK，并验证全部 tail 元素。",
"Choose BLOCK from measured candidates, but never trade away the runtime tail mask for a prettier grid.",
"BLOCK 应从实测候选中选择，但不能为了整齐的 grid 放弃运行期 tail mask。",
"Best BLOCK", "最佳 BLOCK", "int", "Best median", "最佳中位延迟", "ms", ["vector"]),

lesson(5, "explicit-cuda-control", "Explicit CUDA Control and Error Boundaries", "显式 CUDA 控制与错误边界",
"thread blocks, synchronization, nvcc, and reviewable source", "thread block、同步、nvcc 与可审阅源码",
"CUDA C++ makes the scalar thread index, block geometry, launch, synchronization, and error checks explicit. Triton moves many of those choices into a blocked program and compiler. A fair comparison needs both implementations and a toolchain that can actually build the CUDA path.",
"CUDA C++ 显式写出标量 thread index、block 几何、launch、同步和错误检查；Triton 把其中许多选择交给 blocked program 与编译器。公平对照既需要两份实现，也需要真正能构建 CUDA 路径的工具链。",
"Source code availability is not native execution evidence. Without nvcc, a CUDA latency cell must remain unmeasured.",
"有源码不等于完成原生执行。没有 nvcc 时，CUDA latency 必须明确保留为未测。",
"Run the Triton implementation, inspect nvcc availability, and retain an equivalent CUDA C++ source file with launch checks.",
"运行 Triton 实现，检查 nvcc 可用性，并保留带 launch check 的等价 CUDA C++ 源码。",
"Use the explicit CUDA result only after the recorded Toolkit builds and runs it; until then it is a review artifact.",
"只有记录的 Toolkit 真正完成构建与运行后，才使用显式 CUDA 结果；在此之前它只是审阅材料。",
"nvcc available", "nvcc 可用", "bool", "Triton median", "Triton 中位延迟", "ms", ["cuda","best"], "compatibility-probe"),

lesson(6, "memory-coalescing", "Diagnosing Coalescing with Strides", "用 stride 诊断合并访存",
"offset geometry, transactions, and requested bandwidth", "offset 几何、transaction 与请求带宽",
"Coalescing follows the addresses requested by neighboring lanes, not the visual shape of a tensor. The same row-copy source can produce adjacent or strided addresses when its column stride changes. Requested bandwidth is useful only with the stride and byte formula beside it.",
"合并访存取决于相邻 lane 请求的地址，而不是 tensor 看起来的形状。同一份 row-copy 源码只需改变 column stride，就会产生连续或跨步地址。请求带宽必须与 stride 和字节公式一起解释。",
"Adding shared memory before proving an access problem can increase work without fixing the actual address pattern.",
"在尚未证明访存问题前就加入 shared memory，可能增加工作量，却没有修正真正的地址模式。",
"Run one stride-aware Triton copy on contiguous columns and on a stride-two view.",
"让同一个 stride-aware Triton copy 分别处理连续列和 stride=2 的 view。",
"Diagnose addresses first, then use profiler transactions to confirm the mechanism before redesigning the kernel.",
"先诊断地址，再用 profiler transaction 确认机制，最后才重写 kernel。",
"Contiguous median", "连续布局中位延迟", "ms", "Stride-two median", "stride=2 中位延迟", "ms", ["best","cuda"]),

lesson(7, "mask-semantics", "Masks and Reduction Identities", "mask 与 reduction 中性元",
"masked loads, other values, and reduction algebra", "masked load、other 值与归约代数",
"A mask does more than prevent an invalid address: the value supplied for an inactive lane enters subsequent tensor algebra. Sum needs zero, max needs negative infinity, and min needs positive infinity. The correct identity depends on the downstream operation.",
"mask 不只负责阻止无效地址；inactive lane 的填充值还会进入后续 tensor 代数。sum 需要 0，max 需要负无穷，min 需要正无穷。中性元由下游操作决定。",
"Padding an all-negative max reduction with zero silently returns a plausible but impossible answer.",
"全负数 max reduction 若用 0 padding，会悄悄返回看似合理却不可能的结果。",
"Compare correct -inf padding with incorrect zero padding on 1,024 all-negative rows.",
"在 1,024 行全负输入上，对比正确的 -inf padding 与错误的 0 padding。",
"Treat mask values as part of the mathematical specification, not as a memory-safety afterthought.",
"把 mask 填充值写进数学规格，而不是只当作访存安全细节。",
"Correct-mask error", "正确 mask 误差", "scientific", "Zero-pad error", "填 0 误差", "scientific", ["softmax","api"]),

lesson(8, "pointer-layout", "Pointer Arithmetic and Tensor Layout", "指针算术与 tensor 布局",
"logical indices, physical strides, and transposed views", "逻辑索引、物理 stride 与转置 view",
"A logical row and column become a physical address only after multiplying by strides. Writing that equation explicitly lets one Triton kernel accept contiguous, transposed, sliced, or padded views without pretending they share storage order.",
"逻辑行列索引只有乘上 stride 后才成为物理地址。把这个方程显式写出，同一个 Triton kernel 才能处理连续、转置、切片或 padding view，而不会假定它们共享存储顺序。",
"Testing only contiguous tensors can hide a pointer formula that is correct by accident.",
"只测 contiguous tensor，可能让偶然正确的指针公式漏过验证。",
"Copy a transposed non-contiguous view into a contiguous output with explicit row and column strides.",
"使用显式行列 stride，把转置后的 non-contiguous view 复制到连续输出。",
"Make strides part of the public operator contract whenever layout is not fixed by construction.",
"只要布局不是由构造过程固定的，就应把 stride 纳入公开算子 contract。",
"Kernel median", "kernel 中位延迟", "ms", "Requested bandwidth", "请求带宽", "float", ["vector","best"]),

lesson(9, "benchmark-protocol", "Benchmark Protocol and Timing Error", "Benchmark 协议与计时误差",
"warmup, synchronization, quantiles, and JIT", "warmup、同步、分位数与 JIT",
"Asynchronous launches make host wall time and device execution time different quantities. JIT compilation makes the first call different again. A usable report states the timer, warmup, repetitions, synchronization point, and distribution rather than printing one number.",
"异步 launch 让主机 wall time 与设备执行时间成为不同量；JIT 又让首次调用单独成类。可用报告必须写明 timer、warmup、重复次数、同步点和分布，而不是只给一个数字。",
"Including the first JIT call in a steady-state average can dominate the result and invert the decision.",
"把首次 JIT 调用混入稳态平均值，可能完全支配结果并反转决策。",
"Measure one first host call, then retain 40 CUDA-event samples and p20/p50/p80.",
"测量一次首次主机调用，再保留 40 个 CUDA-event 样本及 p20/p50/p80。",
"Publish cold and warm measurements as separate service concerns; never average them together.",
"把 cold 与 warm 测量作为不同服务问题发布，绝不混在一个平均数里。",
"First host call", "首次主机调用", "ms", "Warm p50", "Warm p50", "ms", ["best","api"]),

lesson(10, "roofline-arithmetic-intensity", "Roofline Reasoning before Tuning", "调优前先做 Roofline 判断",
"FLOPs, HBM bytes, arithmetic intensity, and ceilings", "FLOP、HBM 字节、算术强度与上界",
"Arithmetic intensity divides useful operations by required external bytes. Low-intensity pointwise kernels usually need fewer trips to memory; high-intensity matrix products need efficient tensor-core tiling. The model selects the next question but does not identify the achieved hardware bottleneck.",
"算术强度用有效操作数除以外部显存字节。低强度 pointwise kernel 通常要减少往返显存，高强度矩阵乘则要提高 Tensor Core tiling 效率。这个模型用于选择下一问，不能独自定位实测硬件瓶颈。",
"Quoting achieved TFLOP/s for a memory-bound copy, or GB/s for a compute-bound GEMM, hides the relevant ceiling.",
"用 TFLOP/s 描述 memory-bound copy，或用 GB/s 描述 compute-bound GEMM，都会掩盖真正上界。",
"Compute explicit algorithmic intensity for an affine kernel and a square GEMM, then measure each with its relevant unit.",
"显式计算 affine kernel 与方阵 GEMM 的算法算术强度，再使用各自相关的单位测量。",
"Use Roofline to classify the optimization direction; use counters and controlled variants to establish causality.",
"用 Roofline 判断优化方向，再用 counter 与受控变量建立因果。",
"Affine FLOP/byte", "Affine FLOP/byte", "float", "GEMM FLOP/byte", "GEMM FLOP/byte", "float", ["best","matmul"]),

lesson(11, "fused-softmax", "Fused Softmax", "融合 Softmax",
"row programs, stable exponentials, and one-pass traffic", "逐行 program、稳定指数与单遍流量",
"A fused row Softmax loads a row, subtracts its maximum, exponentiates, reduces the denominator, normalizes, and stores once. The power-of-two block is an internal padded shape; masks keep the logical column count exact.",
"融合逐行 Softmax 会读取一行、减去最大值、计算指数、归约分母、归一化并一次写回。2 的幂次 block 是内部 padding 形状，mask 保持逻辑列数准确。",
"A one-row program can exceed practical register capacity for very wide rows; a multi-stage design may then be required.",
"当行极宽时，单行 program 可能超过实际寄存器容量，需要改成多阶段设计。",
"Compare a stable Triton row Softmax with torch.softmax on 4,096 by 1,024 FP32 values.",
"在 4096×1024 FP32 输入上，对比稳定的 Triton row Softmax 与 torch.softmax。",
"Use the fused kernel only inside its validated row-width, dtype, and error envelope.",
"只在已经验证的行宽、dtype 与误差范围内使用融合 kernel。",
"Triton median", "Triton 中位延迟", "ms", "torch.softmax median", "torch.softmax 中位延迟", "ms", ["softmax","best"]),

lesson(12, "reduction-and-scan", "Reduction and Scan", "Reduction 与 Scan",
"tree reduction, prefix dependency, and neutral values", "树形归约、前缀依赖与中性元",
"Reduction collapses a row to one value; scan produces every prefix. Triton expresses both as blocked tensor operations, but their dependency graphs and output traffic differ. Tail padding must still use the correct identity.",
"Reduction 把一行折叠成一个值，scan 则产生每个前缀。Triton 都用 blocked tensor operation 表达，但依赖图与输出流量不同；tail padding 仍需正确中性元。",
"A very large row kept in one program can increase register pressure and reduce active work even when the source is concise.",
"超大行若全部留在一个 program 中，即使源码很短，也可能增加寄存器压力并减少 active work。",
"Run row sum and inclusive cumsum on identical 4,096 by 256 tensors and verify both outputs.",
"在同一个 4096×256 tensor 上运行 row sum 与 inclusive cumsum，并验证两份输出。",
"Select a one-program or multi-stage algorithm from row width and resource evidence, not API brevity.",
"根据行宽和资源证据选择单 program 或多阶段算法，而不是根据 API 长短。",
"Reduction median", "Reduction 中位延迟", "ms", "Scan median", "Scan 中位延迟", "ms", ["api","best"]),

lesson(13, "matmul-tiling", "Matmul Tiling and the Library Boundary", "Matmul tiling 与库函数边界",
"block tiles, tl.dot, L2 reuse, and cuBLAS baselines", "block tile、tl.dot、L2 复用与 cuBLAS 基线",
"A Triton GEMM assigns an output tile to each program, advances through K tiles, accumulates in FP32, and stores once. Tile sizes shape tensor-core use, reuse, and occupancy. Vendor libraries remain the control because standard GEMM is their strongest territory.",
"Triton GEMM 让每个 program 负责一个输出 tile，沿 K 维推进、用 FP32 累加并一次写回。tile 大小共同影响 Tensor Core、复用与 occupancy。标准 GEMM 是厂商库的强项，因此库函数必须保留为 control。",
"One square shape cannot establish parity with cuBLAS across skinny, batched, small, and awkward matrices.",
"一个方阵 shape 不能证明在 skinny、batched、小矩阵和非对齐矩阵上都追平 cuBLAS。",
"Compare a compact teaching Triton FP16 GEMM with torch.mm on one frozen 512-square shape.",
"在固定的 512 方阵上，对比精简教学版 Triton FP16 GEMM 与 torch.mm。",
"Prefer the library for plain GEMM unless custom layout or fused epilogue value survives a representative shape sweep.",
"纯 GEMM 优先使用库；只有自定义布局或融合 epilogue 的收益通过代表性 shape sweep 后，才保留自定义实现。",
"Triton median", "Triton 中位延迟", "ms", "torch.mm median", "torch.mm 中位延迟", "ms", ["matmul","cutlass"]),

lesson(14, "autotune-budget", "Autotune Search and Experiment Budget", "Autotune 搜索与实验预算",
"configuration sets, cache keys, and search cost", "配置集合、cache key 与搜索成本",
"triton.autotune benchmarks eligible configurations when a key changes and caches the winner. This turns meta-parameter selection into measured search, but the first call now includes multiple compilations and executions.",
"triton.autotune 会在 key 改变时 benchmark 候选配置，并缓存胜者。它把 meta-parameter 选择变成实测搜索，但首次调用也会包含多次编译和执行。",
"An autotuned kernel that mutates its output may need a reset hook because every candidate executes during search.",
"会累加或原地修改输出的 autotune kernel 可能需要 reset hook，因为搜索阶段每个候选都会执行。",
"Search three affine BLOCK/warp configurations and separate first host cost from cached warm latency.",
"搜索三组 affine BLOCK/warp 配置，并分开记录首次主机成本与缓存后的 warm 延迟。",
"Spend autotune budget only on dimensions that materially change the optimum and include search cost in deployment planning.",
"只对会显著改变最优解的维度投入 autotune 预算，并把搜索成本纳入部署计划。",
"First autotune call", "首次 autotune 调用", "ms", "Cached warm median", "缓存后中位延迟", "ms", ["api","best"]),

lesson(15, "resources-occupancy", "Registers, Warps, and Occupancy Trade-offs", "寄存器、warp 与 occupancy 权衡",
"BLOCK, num_warps, live values, and latency", "BLOCK、num_warps、live value 与延迟",
"BLOCK and num_warps influence work per program, parallel issue, live values, and the number of resident programs. Timing a controlled configuration sweep reveals sensitivity, but it does not directly report registers or achieved occupancy.",
"BLOCK 与 num_warps 会影响每个 program 的工作量、并行发射、live value 和 resident program 数。受控配置 sweep 能揭示敏感性，但不能直接给出寄存器或 achieved occupancy。",
"Maximizing theoretical occupancy can reduce performance when it forces smaller tiles or more redundant traffic.",
"追求理论最大 occupancy 可能迫使 tile 变小或增加重复流量，反而降低性能。",
"Sweep four BLOCK/warp pairs for the same affine kernel and retain all latency samples.",
"对同一个 affine kernel sweep 四组 BLOCK/warp，并保留全部延迟样本。",
"Use profiler resource fields to explain a timing curve; do not infer occupancy from the fastest point alone.",
"用 profiler 资源字段解释计时曲线，不要只凭最快点反推 occupancy。",
"Best median", "最佳中位延迟", "ms", "Worst/best ratio", "最慢/最佳比值", "ratio", ["best","api"]),

lesson(16, "tensor-cores-dtypes", "Tensor Cores and Dtype Semantics", "Tensor Core 与 dtype 语义",
"input dtype, accumulator precision, throughput, and error", "输入 dtype、累加精度、吞吐与误差",
"tl.dot can lower to target matrix instructions when dtype, shape, and backend permit it. Input storage, multiply precision, accumulator type, and output cast are separate choices. A throughput table is incomplete without error measured against a declared reference.",
"当 dtype、shape 与 backend 允许时，tl.dot 可以降低到目标矩阵指令。输入存储、乘法精度、累加类型和输出 cast 是不同选择；吞吐表若没有相对明确参考的误差，就不完整。",
"Combining FP16, BF16, TF32, and FP8 under one 'Tensor Core' row compares different numerical contracts.",
"把 FP16、BF16、TF32 与 FP8 合并成一行“Tensor Core”结果，实际上混淆了不同数值 contract。",
"Compare BF16 Triton and torch.mm paths, retaining dtype, latency, throughput, and FP32-comparison error.",
"对比 BF16 Triton 与 torch.mm，保留 dtype、延迟、吞吐和相对 FP32 的误差。",
"Choose dtype from an application error envelope first, then optimize the eligible matrix path.",
"先根据业务误差范围选择 dtype，再优化符合条件的矩阵路径。",
"Triton BF16 median", "Triton BF16 中位延迟", "ms", "Library BF16 median", "库 BF16 中位延迟", "ms", ["matmul","cuda"]),

lesson(17, "fused-rmsnorm", "Fused LayerNorm and RMSNorm", "融合 LayerNorm 与 RMSNorm",
"row statistics, FP32 accumulation, and affine output", "逐行统计、FP32 累加与 affine 输出",
"RMSNorm reads a row, accumulates squared values in FP32, computes reciprocal RMS, applies a learned weight, and writes once. LayerNorm adds mean subtraction. Both are memory-sensitive frequent operators whose hidden width sets a practical one-program limit.",
"RMSNorm 读取一行，用 FP32 累加平方和，计算 reciprocal RMS，乘学习权重并一次写回；LayerNorm 还要减均值。二者频繁且对访存敏感，hidden width 决定单 program 的实际边界。",
"A forward-only result says nothing about backward input and weight gradients, which can require additional reductions and synchronization.",
"只测 forward 不能代表 backward；输入梯度与权重梯度可能需要额外归约和同步。",
"Implement fused RMSNorm forward and compare it with an equivalent eager PyTorch expression.",
"实现融合 RMSNorm forward，并与等价 eager PyTorch 表达式对照。",
"Adopt the forward kernel only for validated widths; treat training backward as a separate deliverable.",
"只在验证过的 hidden width 上采用 forward kernel；训练 backward 必须作为独立交付。",
"Triton median", "Triton 中位延迟", "ms", "PyTorch eager median", "PyTorch eager 中位延迟", "ms", ["layernorm","best"]),

lesson(18, "online-softmax-attention", "Online Softmax and Fused Attention", "在线 Softmax 与融合 Attention",
"score tiling, running normalizers, and avoided materialization", "score 分块、运行中归一化量与避免物化",
"Fused attention tiles QK, updates an online Softmax normalizer, and immediately consumes probabilities in PV. The important invariant is that the full score matrix need not reside in HBM. Implementation details vary by backend, head dimension, causal mask, and generation.",
"融合 Attention 会分块计算 QK，更新 online Softmax 归一化量，并立即在 PV 中消费概率。核心不变量是完整 score matrix 不必驻留 HBM；具体实现则随 backend、head dimension、causal mask 与硬件代际变化。",
"FlashAttention is an algorithm family, not a promise that every SDPA call uses one named kernel.",
"FlashAttention 是算法族，不能据此断言每个 SDPA 调用都使用某个固定 kernel。",
"Compare PyTorch causal SDPA with explicitly materialized eager attention and calculate score-tensor bytes.",
"对比 PyTorch causal SDPA 与显式物化的 eager attention，并计算 score tensor 字节数。",
"Use the materialization model to explain scaling, but name the internal backend only when profiler evidence identifies it.",
"用物化模型解释扩展性；只有 profiler 证据定位后，才命名内部 backend。",
"SDPA median", "SDPA 中位延迟", "ms", "Materialized eager median", "物化 eager 中位延迟", "ms", ["attention","sdpa"]),

lesson(19, "numerical-stability", "Numerical Stability and Cast Boundaries", "数值稳定性与 cast 边界",
"max shifting, FP32 accumulation, overflow, and underflow", "max shift、FP32 累加、overflow 与 underflow",
"Low-precision storage does not require low-precision reduction. Stable Softmax subtracts the row maximum before exp and normally accumulates the denominator in FP32. Each cast boundary is therefore an algorithm choice, not formatting.",
"低精度存储不等于低精度归约。稳定 Softmax 会在 exp 前减去行最大值，并通常用 FP32 累加分母。因此每个 cast 边界都是算法选择，不是格式细节。",
"Small random inputs may never exercise overflow, underflow, cancellation, or long-reduction error.",
"小范围随机输入可能永远触发不了 overflow、underflow、抵消或长归约误差。",
"Feed large positive FP16 logits to unshifted eager Softmax and max-shifted Triton Softmax.",
"向未 shift 的 eager Softmax 和 max-shift Triton Softmax 输入大幅正 FP16 logits。",
"Gate optimized kernels with adversarial ranges, NaN/Inf counts, extrema, and a higher-precision reference.",
"用极端范围、NaN/Inf 数量、极值和更高精度参考共同验收优化 kernel。",
"Unstable non-finite values", "不稳定路径非有限值", "int", "Stable max error", "稳定路径最大误差", "scientific", ["softmax","best"]),

lesson(20, "debugging-tools", "Interpreter, Assertions, and Debugging Tools", "Interpreter、断言与调试工具",
"compile-time checks, device checks, interpreter limits, and sanitizers", "编译期检查、设备检查、interpreter 限制与 sanitizer",
"Triton offers static_print/static_assert for compile time and device_print/device_assert for runtime. TRITON_INTERPRET executes programs sequentially on CPU for inspection, with documented dtype and indirect-address limitations. GPU performance must be measured outside interpreter mode.",
"Triton 提供 static_print/static_assert 做编译期检查，device_print/device_assert 做运行期检查。TRITON_INTERPRET 可在 CPU 上顺序解释 program，但对 dtype 与间接地址有已知限制；GPU 性能必须在 interpreter 外测量。",
"Debug output can perturb timing, while interpreter success does not prove GPU scheduling or memory behavior.",
"调试输出会扰动计时；interpreter 通过也不能证明 GPU 调度或访存行为。",
"Probe the four documented debug operators and retain a separate normal GPU correctness run.",
"检查四个文档化调试操作，并单独保留普通 GPU 正确性运行。",
"Use interpreter and assertions to localize errors, then rerun correctness and performance on the target GPU.",
"用 interpreter 与断言定位错误，再回到目标 GPU 重跑正确性与性能。",
"Debug operators present", "可用调试操作数", "int", "Interpreter active", "Interpreter 是否启用", "bool", ["debug","api"], "compatibility-probe"),

lesson(21, "ir-ptx-reading", "From Triton Source to IR and PTX", "从 Triton 源码到 IR 与 PTX",
"TTIR, TTGIR, LLVM IR, PTX, and profiler correlation", "TTIR、TTGIR、LLVM IR、PTX 与 profiler 对照",
"A Triton function passes through high-level tensor IR, target-aware GPU IR, LLVM IR, and a backend assembly stage. Reading these layers can confirm vectorization, masks, loads, and dot lowering. Performance causality still requires runtime samples and hardware counters.",
"Triton function 会经过高层 tensor IR、target-aware GPU IR、LLVM IR 和 backend assembly。阅读这些层可以核查向量化、mask、load 与 dot lowering；性能因果仍需要运行样本和硬件 counter。",
"Spotting one expected PTX mnemonic does not prove the kernel is efficient or that it dominates application time.",
"看到一个预期 PTX mnemonic，不能证明 kernel 高效，也不能证明它支配应用时间。",
"Inspect the reviewed affine source, target identity, mask signal, and the documented dump/profiler path.",
"检查 affine 源码、target 身份、mask 信号，以及文档化 dump/profiler 路径。",
"Use IR to formulate a testable hypothesis, then confirm it with a controlled kernel variant and profiler evidence.",
"用 IR 形成可检验假设，再用受控 kernel 变体与 profiler 证据确认。",
"Source lines", "源码行数", "int", "Lowering path", "Lowering 路径", "text", ["debug","cuda"], "compatibility-probe"),

lesson(22, "torch-compile-integration", "PyTorch Integration with torch.compile", "通过 torch.compile 集成 PyTorch",
"graph capture, Inductor, generated kernels, and cold start", "graph capture、Inductor、生成 kernel 与冷启动",
"torch.compile captures a PyTorch graph and lets Inductor generate fused code, often using Triton on CUDA. This route can remove operator boundaries without maintaining a manual kernel, but compilation, graph breaks, guards, and dynamic shapes become part of the system.",
"torch.compile 捕获 PyTorch graph，并让 Inductor 生成融合代码；在 CUDA 上常会使用 Triton。它可以避免手写 kernel，却把编译、graph break、guard 与动态 shape 纳入系统。",
"Comparing compiled cold start with eager warm time, or attributing all compiled speedup to one generated kernel, produces an invalid conclusion.",
"把 compiled 冷启动与 eager warm 时间相比，或把全部收益归因于一个生成 kernel，都会产生无效结论。",
"Compile a pointwise PyTorch subgraph and record cold execution, compiled warm samples, eager warm samples, and error.",
"编译一个 pointwise PyTorch 子图，记录冷启动、compiled warm、eager warm 与误差。",
"Try compiler fusion before owning a manual kernel when the graph is stable and generated performance meets the gate.",
"当 graph 稳定且生成代码满足 gate 时，先尝试 compiler fusion，再决定是否维护手写 kernel。",
"Compiled cold call", "Compiled 冷启动", "ms", "Compiled warm median", "Compiled warm 中位延迟", "ms", ["pytorch_compile","api"]),

lesson(23, "paged-kv-gather", "Paged KV Cache Addressing", "Paged KV Cache 寻址",
"block tables, logical tokens, physical blocks, and gather layout", "block table、逻辑 token、物理 block 与 gather 布局",
"Paged attention separates a token's logical position from the physical KV block. A block table lookup selects the physical block, while modulo arithmetic selects the slot. The kernel must preserve this indirection without losing width-wise coalescing.",
"Paged attention 把 token 的逻辑位置与物理 KV block 分离。block table lookup 选择物理块，取模选择块内 slot；kernel 既要保持间接寻址，又要保住 width 方向的合并访存。",
"Correct contiguous-cache tests do not cover block-table permutations, partial final blocks, or invalid slot ownership.",
"连续 cache 上的正确性不能覆盖 block-table permutation、最后一个不完整 block 或无效 slot ownership。",
"Implement a Triton paged gather over a randomized logical-to-physical block table and compare advanced indexing.",
"在随机逻辑到物理 block table 上实现 Triton paged gather，并与 advanced indexing 对照。",
"Validate address mapping independently before embedding the gather inside an attention reduction.",
"先独立验证地址映射，再把 gather 嵌入 attention reduction。",
"Triton gather median", "Triton gather 中位延迟", "ms", "PyTorch indexing median", "PyTorch indexing 中位延迟", "ms", ["vector","cuda"]),

lesson(24, "backend-portability", "Backend Portability and the ROCm Boundary", "Backend 可移植性与 ROCm 边界",
"shared source, backend targets, architecture tuning, and unmeasured platforms", "共享源码、backend target、架构调优与未测平台",
"Triton's programming model can target more than one backend, but source portability is only the first layer. Supported operations, code quality, tuning parameters, profiler tools, and numerical behavior can still differ by architecture.",
"Triton 编程模型可以面向多个 backend，但源码可移植只是第一层。支持的 operation、生成代码质量、调优参数、profiler 工具和数值行为仍会随架构变化。",
"A kernel compiled on NVIDIA is not ROCm performance evidence, even if the source contains no CUDA-specific call.",
"kernel 在 NVIDIA 上编译成功，即使没有 CUDA-specific call，也不能当作 ROCm 性能证据。",
"Record the active Triton backend and architecture while keeping the same-source ROCm claim explicitly unexecuted.",
"记录 active Triton backend 与 architecture，并明确保留同源码 ROCm 路径为未执行。",
"Call code portable only after correctness passes on every target; call performance portable only after per-target tuning and measurement.",
"只有所有 target 都通过正确性后，才能称代码可移植；每个 target 都完成调参与实测后，才能称性能可移植。",
"Active backend", "当前 backend", "text", "Target architecture", "目标架构", "text", ["api","tutorials"], "compatibility-probe"),

lesson(25, "dynamic-shapes", "Dynamic Shapes and Specialization", "动态 shape 与特化",
"runtime arguments, constexpr meta-parameters, tails, and cache keys", "运行期参数、constexpr meta-parameter、tail 与 cache key",
"A size used only in masks and grid calculation can remain a runtime argument, allowing one compiled kernel to cover many lengths. Values that shape tl.arange or control compile-time branches must be constexpr and create specialization boundaries.",
"只用于 mask 与 grid 计算的 size 可以保留为运行期参数，让同一 compiled kernel 覆盖多种长度；决定 tl.arange 形状或编译期分支的值必须是 constexpr，并形成特化边界。",
"Marking every shape value constexpr can create compilation churn; making every choice dynamic can prevent useful optimization.",
"把所有 shape 都标成 constexpr 会造成编译抖动；把所有选择都做成动态，又可能阻止有效优化。",
"Run one affine source over three lengths with different tails and retain first/warm results for each.",
"让同一份 affine 源码处理三种长度和不同 tail，并保留每种 shape 的 first/warm 结果。",
"Specialize only on values that change generated structure or produce a measured win large enough to repay compile cost.",
"只对会改变生成结构，或收益足以覆盖编译成本的值做特化。",
"Shapes passed", "通过的 shape 数", "int", "Largest warm median", "最大 warm 中位延迟", "ms", ["api","vector"]),

lesson(26, "persistent-kernels", "Persistent Scheduling and the TMA Boundary", "Persistent 调度与 TMA 边界",
"fixed resident programs, tile loops, launch geometry, and architecture features", "固定 resident program、tile loop、launch 几何与架构特性",
"A persistent kernel launches fewer programs and lets each program loop over multiple tiles. This can amortize scheduling or support producer-consumer pipelines, but it may reduce flexibility and fairness. TMA is a separate architecture-specific data-movement mechanism, not a synonym for persistence.",
"persistent kernel 启动较少 program，让每个 program 循环处理多个 tile。它可能摊薄调度成本或支持 producer-consumer pipeline，也可能降低灵活性与公平性。TMA 是独立的架构相关数据搬运机制，不等于 persistence。",
"Labeling a tile loop 'TMA optimized' without a descriptor, supported load/store path, or profiler evidence is overclaiming.",
"没有 descriptor、受支持的 load/store 路径或 profiler 证据，却把 tile loop 标成“TMA 优化”，属于过度结论。",
"Compare a 256-program persistent affine grid with the standard one-program-per-tile grid; do not use TMA.",
"对比 256-program 的 persistent affine grid 与每 tile 一个 program 的标准 grid；本实验不使用 TMA。",
"Adopt persistence only when its scheduling benefit survives representative concurrency and shape tests.",
"只有调度收益通过代表性并发与 shape 测试后，才采用 persistence。",
"Persistent median", "Persistent 中位延迟", "ms", "Standard-grid median", "标准 grid 中位延迟", "ms", ["tutorials","api"]),

lesson(27, "library-or-custom", "CUTLASS, cuBLAS, cuDNN, or Triton?", "CUTLASS、cuBLAS、cuDNN 还是 Triton",
"library coverage, epilogue fusion, maintainability, and peak tuning", "库覆盖、epilogue 融合、可维护性与峰值调优",
"cuBLAS and cuDNN package highly tuned standard operations; CUTLASS provides C++ templates for architecture-aware kernels; Triton offers a compact DSL for custom blocked dataflow. The decision depends on operation coverage, fusion value, platform range, peak target, and maintenance budget.",
"cuBLAS 与 cuDNN 提供高度调优的标准操作，CUTLASS 用 C++ template 构建架构感知 kernel，Triton 则以紧凑 DSL 表达自定义 blocked dataflow。选择取决于操作覆盖、融合价值、平台范围、峰值目标与维护预算。",
"A custom GEMM that wins one shape but loses library coverage, testing, and future architectures may be a net regression.",
"自定义 GEMM 即使赢了一个 shape，若失去库覆盖、测试与未来架构支持，整体仍可能倒退。",
"Fuse ReLU into a teaching Triton GEMM store and compare with torch.mm plus ReLU.",
"把 ReLU 融合进教学版 Triton GEMM store，并与 torch.mm 加 ReLU 对照。",
"Start from the strongest covered library; own a custom kernel only when the uncovered constraint has measured product value.",
"先从覆盖需求的最强库开始；只有未覆盖约束具有实测产品价值时，才维护自定义 kernel。",
"Fused Triton median", "融合 Triton 中位延迟", "ms", "Library plus ReLU median", "库加 ReLU 中位延迟", "ms", ["cutlass","matmul"]),

lesson(28, "performance-regression-ci", "Performance Regression CI", "性能回归 CI",
"golden outputs, sample distributions, version pins, and warning/error gates", "golden output、样本分布、版本锁定与 warning/error gate",
"A kernel CI job needs correctness and performance contracts. Correctness uses adversarial shapes and golden references; performance compares stable sample summaries on controlled hardware. Version identity travels with the baseline because compiler and backend changes can alter generated code.",
"kernel CI 同时需要正确性与性能 contract。正确性使用极端 shape 与 golden reference；性能在受控硬件上比较稳定样本摘要。版本身份必须跟随 baseline，因为编译器与 backend 变化会改变生成代码。",
"A single noisy sample or a benchmark retained only on a developer laptop cannot support an auditable regression decision.",
"单个噪声样本，或只留在开发者电脑上的 benchmark，都不能支持可审计的回归判断。",
"Collect two independent 30-sample groups and classify their median ratio with frozen warning and error gates.",
"收集两组独立的 30-sample，并按固定 warning/error gate 对中位数比值分类。",
"Use CI as a triage signal: reproduce warnings, block clear regressions, and rebaseline only with an explained environment change.",
"把 CI 当作分诊信号：复现 warning、阻止明确回归，只有环境变化得到解释时才更新 baseline。",
"Candidate/baseline ratio", "Candidate/baseline 比值", "ratio", "CI status", "CI 状态", "text", ["best","api"], "native-backend"),

lesson(29, "selection-framework", "A Triton-versus-CUDA Decision Framework", "Triton 与 CUDA 选型框架",
"performance, shape stability, team skill, lifecycle, platforms, and validation", "性能、shape 稳定性、团队能力、生命周期、平台与验证",
"Tool choice is a constrained engineering decision. Triton often shortens iteration for custom fusion; CUDA exposes lower-level control and the broadest NVIDIA surface; vendor libraries minimize ownership for covered operations. Performance is one axis among six.",
"工具选择是有约束的工程决策。Triton 常能缩短自定义融合迭代；CUDA 提供更底层控制和更广 NVIDIA 能力面；厂商库则降低已覆盖操作的维护成本。性能只是六个维度之一。",
"Declaring Triton a complete CUDA replacement, or CUDA the only serious option, ignores the operator and organization in front of you.",
"把 Triton 宣称为 CUDA 的完全替代，或把 CUDA 当成唯一严肃选择，都会忽略眼前算子与团队的真实约束。",
"Combine one measured affine comparison with an explicit scenario scorecard whose weights remain visible.",
"把一次 affine 实测与权重可见的场景 scorecard 结合起来。",
"Write the decision as constraints, expected benefit, rejected alternatives, and the evidence that would reopen it.",
"把决策写成约束、预期收益、放弃方案，以及什么证据会重新打开决策。",
"Measured Triton/PyTorch ratio", "Triton/PyTorch 实测比值", "ratio", "Pointwise choice", "Pointwise 场景选择", "text", ["tutorials","cuda","cutlass"], "capacity-model"),

lesson(30, "deliverable-kernel", "From Slow Subgraph to Deliverable Kernel", "从慢子图到可交付 kernel",
"baseline, fusion, validation, performance gate, and rollback", "baseline、融合、验证、性能 gate 与回滚",
"A deliverable kernel is more than code that runs. It has a frozen baseline, explicit input contract, adversarial correctness suite, latency distribution, environment identity, stop condition, integration path, and rollback. Optimization ends when the declared gate is met.",
"可交付 kernel 不只是能运行的代码。它需要固定 baseline、明确输入 contract、极端正确性测试、延迟分布、环境身份、停止条件、集成路径与回滚方案；达到声明 gate 后就应停止优化。",
"Without a stop condition, kernel work can continue indefinitely while integration risk and maintenance cost grow.",
"没有停止条件，kernel 优化会无限延伸，集成风险和维护成本却持续增长。",
"Deliver a tanh-approximate GELU Triton kernel with correctness tolerance, repeated timings, minimum performance gate, and PyTorch rollback.",
"交付 tanh 近似 GELU Triton kernel，并固定正确性阈值、重复计时、最低性能 gate 与 PyTorch rollback。",
"Ship only when correctness and performance gates pass together; otherwise keep the documented PyTorch fallback.",
"只有正确性与性能 gate 同时通过才交付；否则保留文档化 PyTorch fallback。",
"PyTorch/Triton speed ratio", "PyTorch/Triton 速度比", "ratio", "Triton median", "Triton 中位延迟", "ms", ["vector","best"]),
]


assert [item["no"] for item in LESSONS] == list(range(1, 31))
